  $( function() {
    var availableTags = [
      "A T Still University-Health",
"A.R.T. Institute of Washington, Inc.",
"AFI Silver Theatre and Cultural Center",
"AIU Online",
"ASA College",
"Abilene Christian University",
"Abraham Baldwin Agricultural College",
"Academy of Art University",
"Academy of Careers and Technology",
"Academy of Fine Arts",
"Accent Reduction Training Association - Atlanta",
"Acton School of Business",
"Adams State University",
"Admissions Office - Chattahoochee Technical College",
"Adrian College",
"Agnes Scott College",
"Air Force Institute of Technology",
"Alabama A&M University",
"Alabama State University",
"Alaska Career College",
"Alaska Pacific University",
"Albany College of Pharmacy and Health Sciences",
"Albany Law School",
"Albany State University",
"Albert Einstein College of Medicine",
"Albertus Magnus College",
"Albion College",
"Albizu University",
"Albright College",
"Alderson Broaddus University",
"Alexandria Technical & Community College",
"Alfred University",
"Alice Lloyd College",
"Allan Hancock College",
"Allegany College of Maryland",
"Allegheny College",
"Allen Community College",
"Alliant International University",
"Alma College",
"Alpena Community College",
"Alvernia University",
"Alverno College",
"Amarillo College - Russell Hall",
"Amberton University",
"American Academy of Dramatic Arts",
"American Film Institute",
"American International College",
"American Jewish University",
"American River College",
"Amherst College",
"Ancilla Domini College",
"Anderson University",
"Andrew Jackson Language Academy",
"Andrews University",
"Angelina College",
"Angelo State University",
"Anne Arundel Community College",
"Annenberg School for Communication",
"Anschutz",
"Antelope Valley College",
"Antioch College",
"Antioch University",
"Antioch University Midwest",
"Antioch University New England",
"Antioch University Seattle",
"Antonin Scalia Law School",
"Appalachian School of Law",
"Appalachian State",
"Appomattox Regional Governor's School",
"Aquinas Institute of Theology",
"Arapahoe Community College",
"Arcadia University",
"Archbishop Spalding High School",
"Argosy University Seattle",
"Argosy University, Atlanta",
"Argosy University, Chicago",
"Argosy University, Dallas",
"Argosy University, Orange County",
"Argosy University, Phoenix",
"Argosy University, Sarasota",
"Argosy University, Twin Cities",
"Arizona Christian University",
"Arizona State University Polytechnic Campus",
"Arizona State University West Campus",
"Arizona Summit Law School",
"Arizona Western College",
"Arkansas Career Development Center",
"Arkansas State University",
"Arkansas State University-Heber Springs",
"Arkansas Tech University",
"Art Academy of Cincinnati",
"ArtCenter College of Design",
"Asbury Theological Seminary",
"Asbury University",
"Asheville-Buncombe Technical Community College",
"Ashland University",
"Ashworth College",
"Athens State University",
"Atlanta Broadcast Institute",
"Atlanta Metropolitan State College",
"Atlantic Cape Community College",
"Atlantic International University",
"Auburn University",
"Auburn University at Montgomery",
"Augsburg University",
"Augusta University - Summerville Campus",
"Augustana College",
"Aurora University",
"Austin College",
"Austin Peay State University",
"Ave Maria School of Law",
"Ave Maria University",
"Averett University",
"Avila University",
"Azusa Pacific University",
"Babson College",
"Bacone College",
"Baker College of Allen Park",
"Baker College of Jackson",
"Baker University",
"Bakersfield College",
"Baldwin Wallace University",
"Ball State University",
"Baptist College of Ministry",
"Baptist University of the Americas",
"Barclay College",
"Bard College",
"Bard College at Simon's Rock",
"Barnard College",
"Barrett, The Honors College at Arizona State University",
"Barry University",
"Barton College",
"Baruch College",
"Bates College",
"Baton Rouge Community College",
"Bay College",
"Bay College West Campus",
"Bay Path University",
"Bay State College",
"Baylor University",
"Belhaven University",
"Bellarmine University",
"Bellevue College",
"Bellevue University",
"Belmont Abbey",
"Belmont University",
"Bemidji State University",
"Benedict College",
"Benedictine College Preparatory",
"Benedictine University",
"Benjamin Franklin Institute of Technology (BFIT)",
"Bennett College",
"Bennington College",
"Bentley University",
"Berea College",
"Bergen Community College",
"Berkeley City College",
"Berkeley College Midtown NYC Campus",
"Berkeley Law Admissions Office",
"Berkeley School of Theology",
"Berklee College of Music",
"Berkshire Community College",
"Berry College",
"Bethany College",
"Bethel College",
"Bethel University",
"Bethlehem College & Seminary",
"Bethune-Cookman University",
"Binghamton University",
"Biola University",
"Birmingham-Southern College",
"Bismarck State College",
"Black Hawk College East Campus",
"Black Hills State University",
"Blackburn College",
"Blanche Ely High School",
"Blinn College-Brenham Campus",
"Bloomfield College",
"Bloomsburg University of Pennsylvania",
"Blue Heron Academy",
"Blue Ridge Job Corps Center",
"Bluefield College",
"Bluefield State College",
"Bluegrass Community & Technical College",
"Bluffton University",
"Bob Jones University",
"Boerigter Center for Calling and Career",
"Boise State University",
"Borough of Manhattan Community College",
"Boston College",
"Boston Institute of Finance",
"Boston University",
"Boston University Fenway Campus",
"Bowdoin College",
"Bowie State University",
"Bowling Green State University",
"Bradley University",
"Brandeis University",
"Brenau University",
"Brescia University",
"Brevard College",
"Brewton-Parker College",
"Briar Cliff University",
"Bridgewater College",
"Bridgewater State University",
"Brigham Young University",
"Brigham Young University-Idaho",
"Brigham Young UniversityâHawaii",
"Bristol Community College",
"Brite Divinity School",
"Bronx Community College",
"Brookdale Community College",
"Brooklyn College",
"Brooklyn Law School",
"Broward College-Weston | Administrative Center",
"Brown Mackie College Michigan City",
"Brown University",
"Bryan College Lions",
"Bryant University",
"Bryant and Stratton Business College",
"Bryn Athyn College",
"Bryn Mawr College",
"Bucknell University",
"Bucks County Community College",
"Buena Vista University",
"Bunker Hill Community College",
"Butler County Community College (BC3 Main Campus)",
"Butler University",
"Butte College",
"CCM",
"CNM Main Campus Student Services Center (SSC)",
"CRAS - Conservatory of Recording Arts and Sciences",
"CSB Media Arts Center",
"CSSC Oxnard College Community Student Services Center",
"CSUDH College of Extended & International Education",
"CUNY College of Staten Island",
"CUNY Graduate Center",
"Cabell County Career Technology Center",
"Cabrillo College",
"Cabrini University",
"Cal Poly Pomona",
"Caldwell Community College and Technical Institute",
"Caldwell University",
"Calhoun Community College",
"California Baptist University",
"California Coast University",
"California College of the Arts",
"California Institute of Integral Studies",
"California Institute of Technology",
"California Institute of the Arts",
"California Lutheran University",
"California Polytechnic State University",
"California State University Channel Islands",
"California State University Long Beach",
"California State University San Marcos",
"California State University, Bakersfield",
"California State University, Chico",
"California State University, East Bay",
"California State University, Fresno",
"California State University, Fullerton",
"California State University, Los Angeles",
"California State University, Monterey Bay",
"California State University, Northridge",
"California State University, Sacramento",
"California State University, San Bernardino",
"California State University, Stanislaus",
"California University of Pennsylvania",
"California Western School of Law",
"Calvin Theological Seminary",
"Calvin University",
"Cambridge Classical Academy",
"Cambridge College",
"Camden County College",
"Cameron University",
"Campbell University",
"Campbellsville University",
"Canisius College",
"Cape Cod Community College Bookstore",
"Capella University",
"Capital University",
"Capitol Technology University",
"Cardinal Stritch University",
"Cardozo School of Law",
"Carl Albert State College",
"Carl Sandburg College",
"Carleton College",
"Carlow University",
"Carlson School of Management",
"Carnegie Mellon University",
"Carroll Community College",
"Carroll University",
"Carson-Newman University",
"Carter School for Peace and Conflict Resolution",
"Carver Center for Arts and Technology",
"Cascadia College",
"Case Western Reserve University",
"Case Western Reserve University School of Law Office of Admissions",
"Casper College",
"Castleton University",
"Catawba College",
"Catawba Valley Community College",
"Catholic Theological Union",
"Cayuga Community College",
"Cazenovia College",
"CaÃ±ada College",
"Cedar Crest College",
"Cedarville University",
"Centenary College of Louisiana",
"Center For Bioethics",
"Center For California Studies",
"Central Alabama Community College",
"Central Baptist College",
"Central Bible College",
"Central College",
"Central Community College - Grand Island",
"Central Connecticut State University",
"Central High Building",
"Central Maine Community College",
"Central Methodist University",
"Central Michigan University",
"Central Ohio Technical College",
"Central Oregon Community College",
"Central Penn College",
"Central School of Practical Nursing",
"Central State University",
"Central Virginia Community College",
"Central Washington University",
"Central Wyoming College",
"Centre College",
"Century College",
"Cerritos College",
"Chabot College",
"Chaffey College",
"Chamberlain University",
"Chaminade University of Honolulu",
"Champlain College",
"Chandler Gilbert Community College - Pecos Campus",
"Chapman University",
"Charleston School of Law",
"Charleston Southern University",
"Charlotte School of Law",
"Charter Oak State College",
"Chatham University",
"Chattanooga State Community College",
"Chemeketa Community College",
"Chesapeake Bay Governors School",
"Chesapeake College",
"Chester College of New England",
"Chestnut Hill College",
"Cheyney University Of Pennsylvania",
"Chicago State University",
"Chowan University",
"Christendom College",
"Christian Brothers University",
"Christopher Newport University",
"Cincinnati Christian University",
"Cincinnati State Technical and Community College",
"Citrus College",
"City College of San Francisco",
"City University of New York",
"City University of Seattle",
"Clackamas Community College",
"Claflin University",
"Claremont Graduate University",
"Claremont McKenna College",
"Clarion University",
"Clark Atlanta University",
"Clark College",
"Clark State College, Springfield",
"Clark University",
"Clarke University",
"Clarkson University",
"Clayton State University",
"Clearwater Christian College",
"Cleary University",
"Clemson Alumni Association",
"Clemson University",
"Cleveland Institute of Art",
"Cleveland State Community College",
"Cleveland State University",
"Clovis Community College",
"Coahoma Community College",
"Coastal Alabama Community College",
"Coastal Carolina University",
"Coastline Community College",
"Cochise College Sierra Vista Campus",
"Coe College",
"Coffeyville Community College",
"Coker University",
"Colby College",
"Colby-Sawyer College",
"Colgate University",
"College For Creative Studies",
"College of Agriculture and Natural Resources",
"College of Biblical Studies",
"College of Central Florida Ocala Campus",
"College of Humanities and Social Sciences",
"College of Idaho",
"College of Lake County",
"College of Law - Syracuse University",
"College of Marin",
"College of Mount Saint Vincent",
"College of Our Lady of the Elms",
"College of San Mateo",
"College of Southern Idaho",
"College of Southern Maryland",
"College of Southern Nevada (South)",
"College of Southern Nevada Charleston Campus",
"College of the Atlantic",
"College of the Canyons",
"College of the Desert",
"College of the Holy Cross",
"College of the Mainland",
"College of the Ozarks",
"College of the Redwoods",
"College of the Sequoias",
"College of the Siskiyous",
"Collin College",
"Colorado Christian University",
"Colorado College",
"Colorado Mesa University",
"Colorado Northwestern Community College",
"Colorado School of Mines",
"Colorado State University",
"Colorado State University Pueblo",
"Colorado Technical University",
"Columbia Basin College",
"Columbia Business School",
"Columbia College",
"Columbia College Chicago",
"Columbia Law School",
"Columbia Southern University",
"Columbia Union College",
"Columbia University",
"Columbus Alternative High School",
"Columbus State Community College",
"Columbus State University",
"Community College Of Denver",
"Community College of Aurora - Lowry Campus",
"Community College of Beaver County",
"Community College of Philadelphia",
"Community College of Vermont (CCV) - Winooski",
"Community College of the Air Force",
"Concord University",
"Concordia Theological Seminary",
"Concordia University",
"Concordia University Chicago",
"Concordia University Irvine",
"Concordia University Texas",
"Concordia University Wisconsin",
"Concordia University, Nebraska",
"Connecticut College",
"Converse College",
"Copiah-Lincoln Community College",
"Copper Mountain College",
"Coppin State University",
"Cornell College",
"Cornell University",
"Cornerstone University",
"Cottey College",
"Covenant College",
"Covenant Theological Seminary",
"Cowley College - Galle-Johnson Hall",
"Craig Newmark Graduate School of Journalism at CUNY",
"Cranbrook Schools",
"Creighton University",
"Crestwood High School",
"Criswell College",
"Cuesta College",
"Cumberland University",
"Curtin University",
"Curtis Institute of Music",
"Cypress College",
"D'Youville College",
"Dakota County Technical College",
"Dakota Ridge High School",
"Dakota State University",
"Dakota Wesleyan University",
"Dallas Baptist University",
"Dallas College Brookhaven Campus",
"Dallas College Cedar Valley Campus",
"Dallas College El Centro Campus",
"Dallas College Mountain View Campus",
"Dallas College North Lake Campus",
"Dallas College Richland Campus",
"Dallas Theological Seminary (DTS Washington, DC)",
"Dalton State College",
"Dana College",
"Darden School of Business - University of Virginia",
"Dartmouth College",
"Davenport University",
"Davidson College",
"Davis & Elkins College",
"Davis Technical College",
"Daytona State College",
"De Anza College",
"DePaul University",
"DePaul University Office of the President",
"DePauw University",
"DeSales University",
"DeVry University",
"Dean College",
"Defense Language Institute â Washington D.C. Office",
"Del Mar College",
"Delaware College of Art and Design (DCAD)",
"Delaware County Community College Bookstore",
"Delaware State University",
"Delaware Valley University",
"Delgado Community College",
"Delta College",
"Delta State University",
"Denison University",
"Denver Seminary",
"Department of Economics",
"Diablo Valley College",
"Dickinson College",
"Dickinson State University",
"Dillard University",
"Divine Word Seminary",
"Dixie State University",
"Doane University",
"Dodge City Community College",
"Dominican School of Philosophy & Theology",
"Dominican University",
"Dominican University of California",
"Dordt University",
"Dowling College",
"Drake University",
"Drew University",
"Drexel University",
"Drury University",
"Dubuque Senior High School",
"Duke University",
"Duke University Sanford School of Public Policy",
"Duke University School of Law",
"Dunlap-Mathis Building",
"Duquesne University",
"Dutchess Community College",
"Eagle Global Advisors",
"Earlham College",
"East Carolina University",
"East Central College",
"East Central University",
"East Los Angeles College",
"East Stroudsburg University of Pennsylvania",
"East Tennessee State University",
"East Texas Baptist University",
"Eastern Connecticut State University",
"Eastern Florida State College",
"Eastern Illinois University",
"Eastern Kentucky University",
"Eastern Maine Community College",
"Eastern Mennonite University",
"Eastern Michigan University",
"Eastern Nazarene College",
"Eastern New Mexico University",
"Eastern Oregon University",
"Eastern University",
"Eastern Washington University",
"Eastman School of Music",
"Eckerd College",
"Edgewood College",
"Edinboro University",
"Edison State Community College",
"Edith Cowan University Joondalup Campus",
"Edmonds College",
"Eindhoven University of Technology",
"Eindhoven University of Technology (Technische Universiteit Eindhoven)",
"El Camino College",
"Elgin Community College",
"Elizabeth City State University",
"Elizabethtown College",
"Ellis University",
"Elmhurst University",
"Elmira College",
"Elon University",
"Emerson College",
"Emory & Henry College",
"Emory University",
"Emory University School of Law",
"Emporia State University",
"Endicott College",
"Erasmus University Rotterdam",
"Erskine College",
"Essex County College",
"Estrella Mountain Community College",
"Eugene Lang College of Liberal Arts at The New School",
"Eugene O'Neill Theater Center",
"Eureka College",
"European University of Tirana",
"Evangel University",
"Everest University",
"Everett Community College",
"FIDM/Fashion Institute of Design & Merchandising",
"Fairfax University of America (FXUA)",
"Fairfield University",
"Fairleigh Dickinson University",
"Fairmont State University",
"Faith Theological Seminary",
"Farmingdale State College",
"Fashion Institute of Technology",
"Faulkner University",
"Fayetteville State University",
"Felician University",
"Fernandina Beach High School",
"Ferris State University",
"Finger Lakes Community College",
"Fisk University",
"Fitchburg State University",
"Five Towns College",
"Flagler College",
"Flashpoint Chicago, a Campus of Columbia College Hollywood",
"Florida A&M University",
"Florida Atlantic University",
"Florida Coastal School Of Law",
"Florida Gateway College",
"Florida Gulf Coast University",
"Florida Institute of Technology",
"Florida International University",
"Florida Memorial University",
"Florida Polytechnic University",
"Florida SouthWestern State College",
"Florida Southern College",
"Florida State College at Jacksonville â Downtown Campus",
"Florida State University",
"Folsom Lake College",
"Fontbonne University",
"Foothill College",
"Fordham University",
"Forsyth Technical Community College Main Campus",
"Fort Hays State University",
"Fort Lewis College",
"Fort Valley State University",
"Fort Wayne Alumni Center",
"Fox Valley Technical College",
"Framingham State University",
"Francis Marion University",
"Franciscan University of Steubenville",
"Franklin & Marshall College",
"Franklin College",
"Franklin Pierce University",
"Franklin University",
"Frederick Community College",
"Freed-Hardeman University",
"Fresno City College",
"Fresno Pacific University",
"Friends University",
"Front Range Community College",
"Frontier Nursing University",
"Frostburg State University",
"Full Sail University",
"Fuller Theological Seminary",
"Fullerton College",
"Furman University",
"G Holmes Braddock Senior High",
"Gadsden State Community College - Wallace Drive Campus",
"Gannon University",
"Gardner-Webb University",
"Garrett College",
"Garrett-Evangelical Theological Seminary",
"Gaston College",
"Gateway Seminary in Phoenix, Arizona",
"Geneva College",
"George Fox University: Newberg Campus",
"George Mason University",
"George Mason University School of Business - Fairfax Campus",
"George Wythe College",
"Georgia College",
"Georgia Gwinnett College",
"Georgia Highlands College",
"Georgia Institute of Technology",
"Georgia Southern University",
"Georgia Southern University Armstrong Campus",
"Georgia Southwestern State University",
"Georgia State University",
"Georgian Court University Bookstore",
"Gettysburg College",
"Gibson, Dunn & Crutcher LLP",
"Gilman School",
"Glendale Community College",
"Glendale University College of Law",
"Glenville State College",
"Global Information Technology",
"Globe Institute Of Technology",
"Goddard College",
"Gogebic Community College",
"Golden Gate University",
"Golden West College",
"Goldey-Beacom College",
"Gonzaga University",
"Gordon College",
"Gordon State College",
"Gordon-Conwell Theological Seminary",
"Goshen College",
"Goucher College",
"Governors State University",
"Grace College",
"Graceland University",
"Graduate School USA",
"Graduate School of Social Service",
"Graduate Theological Union",
"Grambling State University",
"Grand Canyon University",
"Grand Rapids Community College",
"Grand Valley State University",
"Grand View University",
"Great Bay Community College",
"Green Mountain College",
"Green River College",
"Greenfield Community College",
"Greensboro College",
"Greenville Technical College",
"Greenville University",
"Grinnell College",
"Grossmont College",
"Grove City College",
"Guilford College",
"Guilford Technical Community College",
"Gulf Coast State College",
"Guru Nanak Dev University",
"Gustavus Adolphus College",
"Gwynedd Mercy University",
"Halifax Community College",
"Hamilton College",
"Hamline University",
"Hampden-Sydney College",
"Hampshire College",
"Hampton University",
"Hannibal-LaGrange University",
"Hardin-Simmons University",
"Harding University",
"Harford Community College",
"Harold Washington College, City College of Chicago",
"Harper College",
"Harrisburg Area Community College",
"Harrison Middleton University",
"Harry S Truman College",
"Hartnell College",
"Hartt School Community Division",
"Hartwick College",
"Harvard Business School",
"Harvard College",
"Harvard Divinity School",
"Harvard Kennedy School",
"Harvard Law School",
"Harvey Mudd College",
"Hastings College",
"Haverford College",
"HawaiÊ»i Pacific University",
"Hawkeye Community College Main Campus",
"Heartland Community College",
"Heidelberg University",
"Heinz College of Information Systems and Public Policy",
"Henderson State University",
"Hendrix College",
"Henry Clay High School",
"Henry Ford College",
"High Point University",
"Highline College",
"Hillsborough Community College - Plant City Campus",
"Hillsdale College",
"Hinds Community College - Raymond Campus",
"Hiram College",
"Hobart and William Smith Colleges",
"Hodges University",
"Hofstra University",
"Hollins University",
"Holmes Community College",
"Holy Family University",
"Holy Names University",
"Holyoke Community College",
"Hood College",
"Hope College",
"Hope International University (HIU)",
"Houghton College",
"Housatonic Community College",
"Houston Baptist University",
"Houston Community College - Northeast Campus",
"Houston Community College - Spring Branch Campus",
"Howard College",
"Howard Community College",
"Howard Payne University",
"Hudson County Community College",
"Hudson Valley Community College",
"Humanitarian Disaster Institute",
"Humboldt State University",
"Hunter College",
"Huntingdon College",
"Huntington University",
"Husson University",
"Huston-Tillotson University",
"Hutchinson Community College",
"IPR - College of Creative Arts",
"ITT Technical Institute",
"ITT Technical Institute - San Bernardino Campus",
"IUPUC",
"IUPUI",
"Idaho State University",
"Iliff School of Theology",
"Illinois Central College - East Peoria Campus",
"Illinois Institute of Technology",
"Illinois Institute of Technology Rice Campus",
"Illinois Media School",
"Illinois Valley Community College",
"Illinois Wesleyan University",
"Indian River State College",
"Indiana State University",
"Indiana Tech",
"Indiana University Bloomington",
"Indiana University East",
"Indiana University Northwest",
"Indiana University South Bend",
"Indiana University Southeast",
"Indiana University of Pennsylvania",
"Indiana Wesleyan University",
"Inlingua",
"Institute for Training and Development, Inc.",
"Institute of American Indian Arts (IAIA)",
"IntelliTec College in Colorado Springs",
"Interdenominational Theological Center (ITC)",
"International Academy-Design",
"International College of Ministry",
"International School of Management",
"International business school of Washington",
"Inver Hills Community College",
"Iona College",
"Iowa Central Community College",
"Iowa State University",
"Iowa Wesleyan University",
"Irvine Valley College",
"Itawamba Community College",
"Ithaca College",
"Ivy Tech Community College",
"Jackson College",
"Jackson State University",
"Jacksonville State University",
"Jacksonville University",
"James Madison University",
"Janus University",
"Jarvis Christian College",
"Jefferson College",
"Jefferson Community and Technical College",
"Jefferson State Community College",
"John Brown University",
"John Carroll University",
"John Jay College of Criminal Justice",
"John Jay Institute",
"John Tyler Community College",
"Johns Hopkins Bloomberg School of Public Health",
"Johns Hopkins University",
"Johns Hopkins University - Latrobe Hall",
"Johnson & Wales University Providence Campus",
"Johnson & Wales University- Charlotte Campus",
"Johnson C. Smith University",
"Johnson County Community College",
"Johnston Community College",
"Jones College",
"Josef Korbel School of International Studies",
"Judson College",
"June Buchanan School",
"Juniata College",
"Kalamazoo College",
"Kalamazoo Valley Community College",
"Kansas City Art Institute",
"Kansas City Kansas Community College",
"Kansas State University",
"Kansas Wesleyan University",
"KapiÊ»olani Community College",
"KauaÊ»i Community College",
"Kean University",
"Keiser University",
"Kellogg Community College",
"Kennedy-King College",
"Kennesaw State University - Marietta Campus",
"Kent State University",
"Kentucky Christian University",
"Kentucky State University",
"Kentucky Wesleyan College",
"Kenyon College",
"Kettering University",
"Keuka College",
"Keystone College",
"Kilgore College",
"Kingman High School",
"Kingsborough Community College",
"Kirkwood Community College",
"Kishwaukee College",
"Knox College",
"Knox Theological Seminary",
"Knoxville College",
"Kutztown University of Pennsylvania",
"LIU Post",
"LIU Sharks",
"LONG BEACH CITY COLLEGE",
"La Roche University",
"La Salle Language Academy",
"La Salle University",
"La Sierra University",
"LaGuardia Community College",
"Lafayette College",
"Lahainaluna High School",
"Lake Forest College",
"Lake Michigan College",
"Lake Ridge Academy",
"Lake Superior College",
"Lake Superior State University",
"Lake Tahoe Community College",
"Lakeland Community College",
"Lakeland University - Sheboygan Center",
"Lakes Region Community College",
"Lamar University",
"Lancaster Bible College | Capital Seminary & Graduate School",
"Lander University",
"Lane College",
"Lane Community College",
"Laney College",
"Langston University",
"Lansing Community College",
"Laramie County Community College",
"Lasell University",
"Lawrence Technological University",
"Lawrence University",
"Le Moyne College",
"LeMoyne-Owen College",
"LeTourneau University",
"Lebanese American University New York",
"Lebanon Valley College",
"Lee College",
"Lee University",
"Lees-McRae College",
"Leeward Community College",
"Lehigh Carbon Community College",
"Lehigh University",
"Lehigh Valley College",
"Lehman College, CUNY",
"Lenoir-Rhyne University",
"Lesley University",
"Lewis & Clark College",
"Lewis & Clark Law School",
"Lewis University",
"Lewis and Clark Community College Benjamin Godfrey Campus",
"Lewis-Clark State College",
"Liberty University",
"Liberty University School of Law",
"Life Pacific University",
"Limestone University",
"Lincoln College of Technology",
"Lincoln Land Community College",
"Lincoln Memorial University",
"Lincoln University",
"Lindenwood University",
"Lindsey Wilson College",
"Linfield University",
"Linn Benton Community College",
"Lipscomb University",
"Living Arts College",
"Livingstone College",
"Lock Haven University",
"Lone Star College-Houston North Victory",
"Lone Star College-North Harris",
"Lone Star College-Tomball",
"Long Island University Brooklyn",
"Longwood University",
"Lorain County Community College",
"Loras College",
"Lord Fairfax Community College - Fauquier Campus",
"Los Angeles City College",
"Los Angeles Harbor College",
"Los Angeles Southwest College",
"Los Angeles Trade Technical College - LATTC",
"Los Angeles Valley College",
"Los Medanos College",
"Louisiana College",
"Louisiana Delta Community College",
"Louisiana State University",
"Louisiana State University Eunice",
"Louisiana State University Health Sciences Center New Orleans",
"Louisiana State University in Shreveport",
"Louisiana State University of Alexandria",
"Louisiana Tech University",
"Loyola Law School, Los Angeles",
"Loyola Marymount University",
"Loyola University Chicago",
"Loyola University Maryland",
"Loyola University New Orleans",
"Lubbock Christian University",
"Luther College",
"Lutheran School of Theology at Chicago",
"Luzerne County Community College",
"Lycoming College",
"Lynn University",
"Lyon College",
"MACC - Moberly",
"MCPHS University - Boston",
"MSU Denver",
"MTI College",
"Macalester College",
"Macomb Community College",
"Madison Area Technical College",
"Madisonville Community College (North Campus)",
"Madonna University",
"Maharishi International University",
"Maine Media Workshop",
"Malone University",
"Manchester Community College",
"Manchester University",
"Manhattan Christian College",
"Manhattan College",
"Manhattanville College",
"Mansfield University of Pennsylvania",
"Maranatha Baptist University",
"Marian University",
"Marian University Indianapolis",
"Marietta College",
"Marine Corps University",
"Marion Military Institute",
"Marist College",
"Marlboro College",
"Marquette University",
"Mars Hill University",
"Marshall Business School, USC",
"Marshall University",
"Marshalltown Community College",
"Martin Methodist College",
"Martin School of Public Policy and Administration",
"Mary Baldwin University",
"Mary Marauders",
"Marygrove College",
"Maryland Institute College of Art, Main Building",
"Marylhurst University",
"Marymount Manhattan College",
"Marymount University",
"Maryville College",
"Maryville University",
"Marywood University",
"MassBay Community College Wellesley Hills Campus",
"Massachusetts College Of Liberal Arts",
"Massachusetts College of Art and Design",
"Massachusetts Institute of Technology",
"Massachusetts Maritime Academy",
"Massasoit Community College",
"Maurer School of Law",
"Maxwell Air Force Base",
"Mayland Community College",
"McCormick Theological Seminary",
"McDaniel College",
"McHenry County College",
"McKendree University",
"McLennan Community College",
"McMurry University",
"McNeese State University",
"Meadville Lombard Theological School",
"Medgar Evers College",
"Media Institute",
"Medical College of Georgia",
"Medical College of Wisconsin",
"Medical University of South Carolina Libraries",
"Medill School of Journalism, Media, Integrated Marketing Communications",
"Meharry Medical College",
"Memphis College of Art",
"Mendocino College",
"Menlo College",
"Merced College",
"Mercer County Community College",
"Mercer University Atlanta Campus",
"Mercy College",
"Mercyhurst University",
"Meredith College",
"Merrimack College",
"Merritt Community College",
"Mesa Community College",
"Messiah University",
"Methodist Theological School",
"Methodist University",
"Metropolitan College of New York",
"Metropolitan Community College",
"Metropolitan Community College - Maple Woods",
"Metropolitan Community College - Penn Valley",
"Metropolitan Community College - Shipping and Receiving",
"Miami Dade College",
"Miami International University of Art & Design",
"Miami Lakes Educational Center",
"Miami University",
"Michigan Technological University",
"MidAmerica Nazarene University",
"Middle Georgia State University",
"Middle Georgia State University - Cochran Campus",
"Middle Tennessee State University",
"Middlebury College",
"Middlebury Institute of International Studies at Monterey",
"Middlesex College",
"Middlesex Community College",
"Middlesex County Academy for Science, Mathematics & Engineering Technologies",
"Midland College",
"Midway University",
"Midwestern Baptist College",
"Midwestern State University",
"Milano School of Policy, Management and Environment | The New School",
"Miles College",
"Millersville University",
"Milligan University",
"Millikan High School",
"Millikin University",
"Mills College",
"Millsaps College",
"Milwaukee Area Technical College Downtown Milwaukee Campus",
"Milwaukee Institute of Art & Design",
"Milwaukee School of Engineering",
"Mineral Area College",
"Minneapolis College",
"Minneapolis College of Art and Design",
"Minnesota State University Moorhead",
"Minnesota State University, Mankato",
"Minot State University",
"MiraCosta College",
"Misericordia University",
"Mississippi Delta Community College",
"Mississippi Gulf Coast Community College - Perkinston Campus",
"Mississippi State University",
"Mississippi University for Women",
"Mississippi Valley State University",
"Missouri Baptist University",
"Missouri Southern State University",
"Missouri State University",
"Missouri State University-West Plains",
"Missouri University of Science and Technology",
"Missouri Valley College",
"Missouri Western State University",
"Mohave Community College",
"Molloy College",
"Monmouth College",
"Monmouth University",
"Monroe College",
"Montana State University",
"Montana State University Billings",
"Montana Technological University",
"Montclair State University",
"Monterey Peninsula College",
"Montgomery County Community College",
"Montreat College",
"Moody Bible Institute",
"Moraine Valley Community College",
"Moravian College",
"Morehead State University",
"Morehouse College",
"Morgan State University",
"Morningside University",
"Morris College",
"Motion Picture Institute",
"Motlow State Community College Smyrna Campus",
"Mott Community College",
"Mount Aloysius College",
"Mount Holyoke College",
"Mount Mary University",
"Mount Saint Mary College",
"Mount Saint Mary's University, Los Angeles",
"Mount St. Joseph University",
"Mount St. Mary's University",
"Mount Vernon Nazarene University",
"Mount Wachusett Community College",
"Mountain State University",
"Mountwest Community & Technical College",
"Mt. Hood Community College",
"Mt. San Antonio College",
"Mt. San Jacinto College",
"Muhlenberg College",
"Mullins High School",
"Murdoch University",
"Murray State University",
"Musicians Institute",
"Muskegon Community College",
"Muskingum University",
"NCTC North Central Texas College - Gainesville Campus",
"NHTI-Concord's Community College",
"NIACC - North Iowa Area Community College",
"NYU School of Law",
"Naperville North High School",
"Naropa University",
"Nashotah House Theological Seminary",
"Nashua Community College",
"Nashville State Community College",
"Nassau Community College",
"National Intelligence University",
"National Louis University - Chicago campus",
"National University",
"National University of Health Sciences",
"Naugatuck Valley Community College",
"Naval Postgraduate School",
"Navarro College",
"Nazareth College",
"Nebraska Wesleyan University",
"Neumann University",
"Neumont College of Computer Science",
"Nevada State College",
"New Century College",
"New Charter University",
"New College Franklin",
"New College of Florida",
"New England College",
"New England Conservatory of Music",
"New England Institute of Art",
"New England Law | Boston",
"New England School of Communications",
"New England School of Photography",
"New Horizons",
"New Jersey City University",
"New Jersey Institute of Technology",
"New Mexico Highlands University",
"New Mexico Institute of Mining and Technology",
"New Mexico Military Institute",
"New Mexico State University",
"New Orleans Baptist Theological Seminary",
"New River Community College",
"New Saint Andrews College",
"New York Film Academy | New York",
"New York Institute of Finance",
"New York Law School",
"New York Medical College",
"New York University",
"New York University Tandon School of Engineering",
"Newberry College",
"Newbury College Adult & Pro",
"Newman University",
"Niagara University",
"Nicholls State University",
"Nichols College",
"Nicolet College",
"Niles West High School",
"Norco College",
"Norfolk State University",
"Normandale Community College",
"North Carolina Agricultural and Technical State University",
"North Carolina Central University",
"North Carolina State University",
"North Carolina Wesleyan College",
"North Central College",
"North Central Michigan College",
"North Central University",
"North Dakota State University",
"North Greenville University",
"North Hagerstown High School",
"North Hennepin Community College",
"North Idaho College",
"North Park University",
"North Seattle College",
"NorthWest Arkansas Community College",
"Northampton Community College",
"Northcentral University",
"Northeast Alabama Community College",
"Northeast Community College",
"Northeast Mississippi Community College",
"Northeast State Community College",
"Northeast Wisconsin Technical",
"Northeastern Illinois University",
"Northeastern State University",
"Northeastern University",
"Northern Arizona University",
"Northern Illinois University",
"Northern Kentucky University",
"Northern Michigan University",
"Northern Oklahoma College",
"Northern Seminary",
"Northern State University",
"Northern Vermont University - Johnson",
"Northern Vermont University-Lyndon",
"Northern Virginia Community College - Alexandria Campus",
"Northern Virginia Community College - Annandale Campus",
"Northland College",
"Northside College Prep",
"Northwest Florida State College",
"Northwest Mississippi Community College",
"Northwest Missouri State University",
"Northwest Nazarene University",
"Northwest University",
"Northwest Vista College",
"Northwestern College",
"Northwestern Michigan College",
"Northwestern Oklahoma State University",
"Northwestern State University",
"Northwestern University",
"Northwood University",
"Norwalk Community College",
"Norwich University",
"Notre Dame College Prep",
"Notre Dame de Namur University",
"Notre Dame of Maryland University",
"Nova Southeastern University",
"OSF Saint Francis Medical Center",
"Oakland University",
"Oakmont Regional High School",
"Oakton Community College",
"Oakwood University",
"Oberlin College",
"Oblate School",
"Occidental College",
"Ocean County College",
"Oglethorpe University",
"Ohio Dominican University",
"Ohio Northern University",
"Ohio State University Agricultural Technical Institute",
"Ohio University",
"Ohio Wesleyan University",
"Oklahoma Baptist University",
"Oklahoma Christian University",
"Oklahoma City Community College",
"Oklahoma City University",
"Old Dominion University",
"Olin College of Engineering",
"Olivet College",
"Olivet Nazarene University",
"Olympic College",
"Online MBA Schiller International University",
"Onondaga Community College",
"Oral Roberts University",
"Orange Coast College",
"Orange County Community College (SUNY Orange)",
"Oregon State University",
"Otis College of Art and Design",
"Ottawa University",
"Otterbein University",
"Ouachita Baptist University",
"Owens Community College",
"Oxford Academy Foundation",
"Ozarks Technical Community College",
"Pace University",
"Pacific College of Health and Science - Chicago",
"Pacific Lutheran University",
"Pacific McGeorge School of Law",
"Pacific Oaks College in San Jose",
"Pacific School of Religion",
"Pacific Union College",
"Pacific University Forest Grove Campus",
"Pacifica Graduate Institute",
"Paine College",
"Palm Beach Atlantic University",
"Palm Beach State College",
"Palo Alto College",
"Palomar College",
"Paradise Valley Community College",
"Park Vista Community High School",
"Parkland College Online",
"Parsons School of Design | The New School",
"Pasadena City College",
"Passaic County Community College",
"Patrick Henry College",
"Patten University",
"Patterson School of Diplomacy",
"Paul Mitchell The School Atlanta",
"Peace Operations Training Institute",
"Pellissippi State Community College",
"Penn Graduate School of Education",
"Penn State Abington",
"Penn State Altoona",
"Penn State Behrend",
"Penn State Berks",
"Penn State Great Valley: School of Graduate Professional Studies",
"Penn State Harrisburg",
"Penn State New Kensington",
"Penn State Scranton",
"Penn State University",
"Penn Wood High School - Green Avenue Campus",
"Pennsylvania College-Art-Design",
"Pensacola Christian College",
"Pensacola State College",
"Pepperdine University",
"Pfeiffer University",
"Philander Smith College",
"Phillips Graduate University",
"Phillips Theological Seminary",
"Phoenix College",
"Piedmont University",
"Piedmont Virginia Community College",
"Pierce College",
"Pierce College Fort Steilacoom",
"Pierce College Puyallup",
"Pikes Peak Community College",
"Pima Community College",
"Pine Manor College Child Study Center",
"Pitt Community College",
"Pittsburg State University",
"Pitzer College",
"Plaza College",
"Plymouth State University",
"Point Loma Nazarene University",
"Point Park University",
"Polk State College",
"Pomona College",
"Portland State University",
"Post University",
"Prairie State College",
"Prairie View A&M University",
"Pratt Institute",
"Presbyterian College",
"Presidio Graduate School",
"Prince George's Community College - Main Campus",
"Princeton School of Public and International Affairs",
"Princeton Theological Seminary",
"Princeton University",
"Principia College",
"Providence College",
"Purchase College",
"Purdue University",
"Purdue University Fort Wayne",
"Purdue University Northwest - Hammond Campus",
"Queens College, City University of New York",
"Queens University of Charlotte",
"Quincy University",
"Quinebaug Valley Community College",
"Quinnipiac University",
"Quinsigamond Community College",
"Radford University",
"Ramapo College of New Jersey",
"Randolph College",
"Randolph-Macon College",
"Rappahannock Community College",
"Raritan Valley Community College",
"Rawls College of Business",
"Reading Area Community College",
"Red Rocks Community College",
"Redeemer Seminary",
"Reed College",
"Reedley College",
"Reformed Theological Seminary, Washington D.C.",
"Regent University",
"Regis College",
"Regis University (Northwest Denver Campus)",
"Rensselaer Polytechnic Institute",
"Reynolds Community College (Parham Campus)",
"Rhode Island College",
"Rhode Island School of Design (RISD)",
"Rhodes College",
"Rice University",
"Richard Bland College of William & Mary",
"Richard J. Daley College",
"Richardson High School",
"Richland Northeast High School",
"Rider University",
"Ringling College of Art and Design",
"Rio Hondo College",
"Rio Salado College",
"Ripon College",
"Riverside City College",
"Rivier University",
"Roanoke College",
"Robert Morris University",
"Roberts Wesleyan College",
"Rochester Community and Technical College",
"Rochester Institute of Technology",
"Rock Falls Township High School",
"Rock Valley College",
"Rockford University",
"Rockhurst University",
"Rockland Community College",
"Rocky Mountain College",
"Roger Williams University",
"Rogers Park Montessori School",
"Rogers State University",
"Rogue Community College - Redwood Campus",
"Rollins College",
"Roosevelt University",
"Rosalind Franklin University of Medicine and Science",
"Rose State College",
"Rose-Hulman Institute of Technology",
"Roseman University of Health Sciences",
"Rosemont College",
"Rotterdam School of Management, Erasmus University",
"Rowan College of South Jersey Cumberland Campus",
"Rowan University",
"Rowan-Cabarrus Community College",
"Rush University College of Health Sciences",
"Russell Sage College",
"Rust College",
"Rutgers Robert Wood Johnson Medical School",
"Rutgers University - Newark Campus",
"Rutgers UniversityâCamden",
"SIT | School for International Training",
"SLCC",
"SUNY Adirondack",
"SUNY Brockport",
"SUNY Broome Community College",
"SUNY Buffalo State College",
"SUNY College at Old Westbury",
"SUNY College of Environmental Science and Forestry",
"SUNY Corning Community College",
"SUNY Cortland",
"SUNY Empire State College Administrative Offices",
"SUNY Geneseo",
"SUNY Maritime College",
"SUNY Morrisville",
"SUNY Oneonta",
"SUNY Oswego",
"SUNY Potsdam",
"SUNY Schenectady County Community College",
"SUNY Ulster",
"SUNY Upstate Medical University",
"Sacramento City College",
"Sacred Heart University",
"Saddleback College",
"Saginaw Valley State University",
"Saint Anselm College",
"Saint Augustineâs University",
"Saint Cloud State University",
"Saint Elizabeth University",
"Saint Francis University",
"Saint John's University",
"Saint Joseph's University",
"Saint Leo University",
"Saint Louis University",
"Saint Louis University School of Medicine",
"Saint Mary's College",
"Saint Mary's College of California",
"Saint Mary's University of Minnesota",
"Saint Mary-of-the-Woods College",
"Saint Paul's College",
"Saint Peter's University",
"Saint Vincent College",
"Saint Xavier University",
"Salem College",
"Salem Community College",
"Salem State University",
"Salem University",
"Salisbury University",
"Salish Kootenai College",
"Salt Institute-Documentary",
"Salve Regina University",
"Sam Houston State University",
"Samford University",
"San Antonio College",
"San Bernardino Valley College",
"San Diego City College",
"San Diego Mesa College",
"San Diego Miramar College",
"San Diego State University",
"San Diego University for Integrative Studies and English School",
"San Francisco Art Institute",
"San Francisco Conservatory of Music",
"San Francisco State University",
"San Joaquin Delta College",
"San JosÃ© City College",
"San JosÃ© State University",
"Sandhills Community College",
"Sandra Day O'Connor College of Law",
"Sanford-Brown College - Chicago",
"Santa Ana College",
"Santa Barbara City College",
"Santa Clara University",
"Santa Fe College",
"Santa Fe Community College",
"Santa Fe University of Art and Design",
"Santa Monica College",
"Santa Rosa Junior College",
"Santiago Canyon College",
"Sarah Lawrence College",
"Sauk Valley Community College",
"Saybrook University",
"School of Diplomacy and International Relations",
"School of Engineering and Applied Science",
"School of Theology and Ministry",
"School of Visual Arts",
"School of the Art Institute of Chicago",
"School of the Museum of Fine Arts at Tufts University",
"Schoolcraft College",
"Schreiner University",
"Scott Community College",
"Scottsdale Community College",
"Scripps College",
"Seattle Central College",
"Seattle Pacific University",
"Seattle University",
"Seminole State College Student Center",
"Seton Hall University",
"Seton Hill University",
"Sewanee: The University Of The South",
"Seward County Community College",
"Shaw University",
"Shawnee State University",
"Shelton State Community College",
"Shenandoah University",
"Shepherd University",
"Sherman School of Excellence",
"Shippensburg University",
"Shorter University",
"Siena College",
"Siena Heights University",
"Sierra College",
"Sierra Nevada University",
"Silver School of Social Work",
"Simmons University",
"Simpson College",
"Sinclair Community College",
"Skidmore College",
"Skyline College",
"Slippery Rock University",
"Smith College",
"Soka University of America",
"Solano Community College",
"Sonoma State University",
"South Brunswick High School",
"South Carolina State University",
"South Dakota Mines",
"South Dakota State University",
"South Georgia State College",
"South Piedmont Community College",
"South Puget Sound Community College",
"South Seattle College",
"South Suburban College",
"South Texas College of Law Houston",
"Southeast Community College",
"Southeast Missouri State University",
"Southeastern Baptist Theological Seminary",
"Southeastern Illinois College",
"Southeastern Louisiana University",
"Southeastern University",
"Southern Adventist University",
"Southern Arkansas University",
"Southern Connecticut State University",
"Southern Crescent Technical College - Griffin Campus",
"Southern Evangelical Seminary",
"Southern Illinois University",
"Southern Illinois University Edwardsville",
"Southern Maine Community College",
"Southern Methodist University",
"Southern Nazarene University",
"Southern New Hampshire University",
"Southern Oregon University",
"Southern University and A&M College",
"Southern University at New Orleans",
"Southern Utah University",
"Southern Vermont College",
"Southern Virginia University",
"Southern Wesleyan University",
"Southwest Baptist University",
"Southwest Minnesota State University",
"Southwest Mississippi Community College",
"Southwest Tennessee Community College - Union Avenue Campus",
"Southwest Texas Junior College",
"Southwestern Adventist University",
"Southwestern Assemblies of God University (SAGU)",
"Southwestern Baptist Theological Seminary",
"Southwestern College",
"Southwestern College - Professional Studies",
"Southwestern Law School",
"Southwestern Michigan College",
"Southwestern Oklahoma State University",
"Southwestern Oklahoma State University Bookstore",
"Southwestern University",
"Spalding University",
"Spartanburg Methodist College",
"Specs Howard School of Media Arts",
"Spelman College",
"Spokane Falls Community College",
"Spoon River College",
"Spring Arbor University",
"Spring Hill College",
"Springfield Technical Community College",
"St Gregory's University",
"St John's University Queens Campus",
"St Johns River State College",
"St Mary's School",
"St. Ambrose University",
"St. Andrews University",
"St. Anthony Middle School",
"St. Bonaventure University",
"St. Catherine University",
"St. Charles Community College (SCC)",
"St. Clair County Community College",
"St. Edward's University",
"St. Francis College",
"St. Francis de Sales High School",
"St. John Fisher College",
"St. John's College",
"St. John's College of Nursing",
"St. John's University",
"St. Josephâs College New York",
"St. Kates",
"St. Lawrence University",
"St. Louis Christian College",
"St. Louis Community College",
"St. Louis Community College - Meramec",
"St. Mary's College of Maryland",
"St. Mary's University",
"St. Norbert College",
"St. Olaf College",
"St. Petersburg/Gibbs Campus",
"St. Thomas Aquinas College",
"St. Thomas University",
"Stanford Graduate School of Business",
"Stanford Law School",
"Stanford University",
"Stanly Community College",
"Stark State College",
"State Fair Community College",
"State University of New York at Fredonia",
"State University of New York at New Paltz",
"State University of New York at Plattsburgh",
"Steele Canyon High School",
"Stephen F. Austin State University",
"Stephens College",
"Sterling College",
"Stetson University",
"Stevens Institute of Technology",
"Stillman College",
"Stockbridge High School",
"Stockton University",
"Stone Mountain High School",
"Stonehill College",
"Stony Brook University",
"Stony Brook University Southampton - Gymnasium",
"Strake Jesuit College Preparatory",
"Suffolk County Community College Grant Campus",
"Suffolk University",
"Sul Ross State University",
"Susquehanna University",
"Swarthmore College",
"Sweet Briar College",
"Tacoma Community College",
"Talbot School of Theology",
"Talladega College",
"Tallahassee Community College",
"Tarleton State University",
"Tarrant County College - Northeast Campus",
"Tarrant County College District Office",
"Taylor University",
"Teachers College, Columbia University",
"Temple University",
"Tennessee State University",
"Tennessee Tech University",
"Tennessee Temple University",
"Tennessee Wesleyan University",
"Terra State Community College",
"Texarkana College",
"Texas A&M International University",
"Texas A&M University",
"Texas A&M University - Kingsville",
"Texas A&M University Texarkana",
"Texas A&M University-Commerce",
"Texas A&M University-Corpus Christi",
"Texas A&M University-San Antonio",
"Texas Christian University",
"Texas Lutheran University",
"Texas Southern University",
"Texas State University",
"Texas Tech University",
"Texas Wesleyan University",
"Texas Woman's University",
"The American Musical and Dramatic Academy",
"The Art Institute of Atlanta",
"The Art Institute of Austin",
"The Art Institute of California - Orange County",
"The Art Institute of Chicago",
"The Art Institute of Colorado",
"The Art Institute of Fort Lauderdale",
"The Art Institute of Jacksonville",
"The Art Institute of Las Vegas",
"The Art Institute of Philadelphia",
"The Art Institute of Pittsburgh",
"The Art Institute of Seattle",
"The Art Institutes - New York",
"The Bush School of Government and Public Service",
"The Christ College of Nursing and Health Sciences",
"The Citadel",
"The City College of New York",
"The College at Southeastern",
"The College of New Jersey",
"The College of Saint Rose",
"The College of St. Scholastica",
"The Colony HS Indoor Facility",
"The Cooper Union",
"The Creative Circus",
"The Evergreen State College",
"The Fletcher School at Tufts University",
"The Illinois Institute of Art - Chicago",
"The Juilliard School",
"The King's College",
"The Lee Strasberg Theatre & Film Institute",
"The Los Angeles Film School",
"The Master's University",
"The New School",
"The Ohio State University",
"The Ohio State University at Newark",
"The Rockefeller University",
"The Savannah College of Art and Design",
"The Southern Baptist Theological Seminary",
"The University of Akron",
"The University of Alabama",
"The University of Alabama in Huntsville",
"The University of Arizona",
"The University of Baltimore",
"The University of Chicago",
"The University of Findlay",
"The University of Iowa",
"The University of Memphis Lambuth Campus",
"The University of New Mexico",
"The University of New Orleans",
"The University of Oklahoma",
"The University of Scranton",
"The University of Southern Mississippi",
"The University of Tampa",
"The University of Tennessee at Chattanooga",
"The University of Texas Health Science Center at Houston",
"The University of Texas Permian Basin",
"The University of Texas Rio Grande Valley",
"The University of Texas at Austin",
"The University of Texas at El Paso",
"The University of Texas at San Antonio",
"The University of Texas at Tyler Graduate School",
"The University of Toledo",
"The University of Tulsa",
"The University of Utah",
"The University of Virginia's College at Wise",
"The University of Western Australia",
"Thiel Audio Products",
"Thiel College",
"Thomas Aquinas College",
"Thomas Dale High School - Main Campus",
"Thomas Edison State University",
"Thomas Jefferson School of Law",
"Thomas More College of Liberal Arts",
"Thomas More University",
"Thomas Nelson Community College",
"Thunderbird School of Global Management",
"Tiffin University",
"Toccoa Falls College",
"Tompkins Cortland Community College",
"Tougaloo College",
"Touro College",
"Towson University",
"Transylvania University",
"Trevecca Nazarene University",
"Tri-County Technical College",
"Trident Technical College",
"Trident University",
"Trine University",
"Trinity Christian College",
"Trinity College",
"Trinity Evangelical Divinity School",
"Trinity International University",
"Trinity Valley Community College",
"Triton College",
"Troy University",
"Troy University - Fort Walton Beach Support Center",
"Troy University - Phenix City Campus",
"Truckee Meadows Community College (TMCC)",
"Truman State University",
"Tufts University",
"Tulane University",
"Tulane University School of Public Health and Tropical Medicine",
"Tulsa Community College Northeast Campus",
"Tusculum University",
"Tuskegee University",
"Tyler Junior College",
"UA - Eller College of Management",
"UALR William H. Bowen School of Law",
"UC Hastings College of the Law",
"UCSD-RIMAC ARENA",
"UChicago Medicine",
"UIC Global",
"UIC John Marshall Law School",
"UIC Technical and Professional Services",
"UMBC Information Technology and Engineering (ITE) Building",
"US Army War College",
"US Naval War College",
"UT Southwestern Medical Center",
"UTMB Health - University of Texas Medical Branch at Galveston",
"UTRGV - The University of Texas Rio Grande Valley",
"UW-Green Bay | Marinette Campus",
"UW-Milwaukee at Washington County",
"UW-Milwaukee at Waukesha",
"UW-Oshkosh at Fox Cities",
"UW-Platteville at Baraboo Sauk County",
"UW-Platteville at Richland",
"UW-Stevens Point at Wausau",
"UW-Whitewater at Rock County",
"UWM CLS Department of History",
"Ultimate Medical Academy (Online)",
"Union County College",
"Union Institute & University",
"Union University",
"United States Coast Guard Academy",
"United States Merchant Marine Academy",
"United States Naval Academy",
"United World College USA",
"Unity College",
"Universal Technical Institute",
"University Blvd & Buckingham Dr",
"University Of Montevallo",
"University Of The Southwest",
"University at Albany",
"University at Buffalo",
"University of Advancing Technology",
"University of Akron School of Law",
"University of Alabama at Birmingham",
"University of Alaska Anchorage",
"University of Alaska Fairbanks",
"University of Arizona Global Campus",
"University of Arkansas",
"University of Arkansas - Fort Smith",
"University of Arkansas Community College at Batesville",
"University of Arkansas Community College at Morrilton",
"University of Arkansas Pine Bluff",
"University of Arkansas at Little Rock",
"University of Arkansas â Pulaski Technical College",
"University of Bridgeport",
"University of California Irvine",
"University of California Merced",
"University of California San Diego",
"University of California Santa Cruz",
"University of California, Davis",
"University of California, Los Angeles",
"University of California, Riverside",
"University of California, Santa Barbara",
"University of Central Arkansas",
"University of Central Florida",
"University of Central Missouri",
"University of Central Oklahoma",
"University of Charleston",
"University of Cincinnati",
"University of Colorado Boulder",
"University of Colorado Colorado Springs",
"University of Colorado Denver",
"University of Colorado Health Science Center",
"University of Connecticut",
"University of Connecticut - Avery Point Campus",
"University of Connecticut-Stamford Campus",
"University of Dallas",
"University of Dayton",
"University of Delaware",
"University of Denver",
"University of Detroit Mercy",
"University of Dubuque",
"University of Evansville",
"University of Florida",
"University of Florida Levin College of Law",
"University of Georgia",
"University of Hartford",
"University of HawaiÊ»i at Hilo",
"University of HawaiÊ»i at MÄnoa",
"University of HawaiÊ»i â West OÊ»ahu",
"University of Holy Cross",
"University of Houston",
"University of Houston-Clear Lake",
"University of Houston-Downtown (UHD)",
"University of Houston-Victoria",
"University of Idaho",
"University of Illinois Springfield",
"University of Illinois at Chicago",
"University of Indianapolis",
"University of Jamestown",
"University of Kansas",
"University of Kentucky",
"University of Kentucky J. David Rosenberg College of Law",
"University of La Verne",
"University of Louisiana Monroe",
"University of Louisiana at Lafayette",
"University of Louisville",
"University of Maine",
"University of Maine Farmington",
"University of Maine at Augusta",
"University of Maine at Fort Kent",
"University of Maine at Machias",
"University of Maine at Presque Isle",
"University of Mary Hardin-Baylor",
"University of Mary Washington",
"University of Maryland",
"University of Maryland - Department of Economics",
"University of Maryland Eastern Shore",
"University of Maryland Global Campus",
"University of Maryland School of Law",
"University of Maryland, Baltimore",
"University of Maryland, Baltimore County",
"University of Massachusetts Amherst",
"University of Massachusetts Boston",
"University of Massachusetts Dartmouth",
"University of Massachusetts Lowell",
"University of Memphis",
"University of Metaphysical Sciences",
"University of Miami",
"University of Michigan",
"University of Michigan Law School",
"University of Michigan-Dearborn",
"University of Michigan-Flint",
"University of Minnesota",
"University of Minnesota Duluth",
"University of Minnesota Law School",
"University of Minnesota, Morris",
"University of Mississippi",
"University of Missouri",
"University of Missouri-Kansas City: Volker Campus",
"University of Missouri-St. Louis",
"University of Mobile",
"University of Montana",
"University of Mount Olive",
"University of Mount Union",
"University of Nebraska Kearney",
"University of Nebraska Omaha",
"University of Nebraska-Lincoln",
"University of Nevada, Las Vegas",
"University of Nevada, Reno",
"University of New England - Biddeford Campus",
"University of New Hampshire",
"University of New Hampshire School of Law",
"University of New Haven",
"University of North Alabama",
"University of North Carolina Asheville",
"University of North Carolina Greensboro",
"University of North Carolina School of the Arts",
"University of North Carolina Wilmington",
"University of North Carolina at Charlotte",
"University of North Carolina at Pembroke",
"University of North Dakota",
"University of North Florida",
"University of North Georgia",
"University of North Texas",
"University of Northern Colorado",
"University of Northern Iowa",
"University of Northern Va",
"University of Northwestern â St. Paul",
"University of Notre Dame",
"University of Oklahoma College of Law",
"University of Oregon",
"University of Pennsylvania",
"University of Phoenix",
"University of Pittsburgh",
"University of Pittsburgh at Bradford",
"University of Pittsburgh at Johnstown",
"University of Portland",
"University of Providence",
"University of Puget Sound",
"University of Redlands",
"University of Rhode Island",
"University of Rhode Island Providence Campus",
"University of Richmond",
"University of Rio Grande",
"University of SC Union",
"University of Saint Francis",
"University of San Diego",
"University of San Francisco",
"University of Santa Monica",
"University of Science and Arts of Oklahoma",
"University of Sioux Falls",
"University of South Alabama",
"University of South Carolina",
"University of South Carolina Aiken",
"University of South Carolina Salkehatchie",
"University of South Carolina Upstate",
"University of South Dakota",
"University of South Florida",
"University of South Florida St. Petersburg Campus",
"University of Southern California",
"University of Southern Indiana",
"University of Southern Maine",
"University of St. Thomas",
"University of Tennessee",
"University of Tennessee College of Law",
"University of Tennessee at Martin",
"University of Texas at Arlington",
"University of Texas at Dallas",
"University of Utah S.J. Quinney College of Law",
"University of Vermont",
"University of Virginia School of Law",
"University of Virginia: Department of Politics",
"University of Washington Bothell",
"University of Washington Tacoma",
"University of West Alabama",
"University of West Florida",
"University of West Georgia",
"University of Wisconsin-Green Bay",
"University of Wisconsin-Milwaukee",
"University of Wisconsin-Oshkosh",
"University of Wisconsin-Platteville",
"University of Wisconsin-River Falls",
"University of Wisconsin-Stout",
"University of Wisconsin-Superior",
"University of Wisconsin-Whitewater",
"University of WisconsinâEau Claire",
"University of WisconsinâLa Crosse",
"University of WisconsinâParkside",
"University of WisconsinâStevens Point",
"University of Wyoming",
"University of the Cumberlands",
"University of the Incarnate Word",
"University of the Ozarks",
"University of the Pacific",
"University of the Sciences in Philadelphia",
"Upper Iowa University - Fayette",
"Urbana University",
"Ursinus College",
"Utah State University",
"Utah State University Eastern",
"Utah Valley University",
"Utica College",
"Valdosta State University",
"Valencia College",
"Valparaiso University",
"Van Andel Graduate School of Statesmanship",
"Vanderbilt Law School",
"Vanderbilt University",
"Vanderbilt Universityâs Peabody College",
"Vanguard University",
"Varsity College Planning",
"Vassar College",
"Ventura College",
"Vermilion Community College",
"Vermont College of Fine Arts",
"Vermont Law School",
"Vermont Technical College",
"Victor Valley College",
"Victoria College",
"Villanova University",
"Villanova University Charles Widger School of Law",
"Vincennes University",
"Vincennes University Jasper",
"Virginia Clg School-Constructn",
"Virginia Commonwealth University",
"Virginia Military Institute",
"Virginia Polytechnic Institute and State University",
"Virginia State University",
"Virginia Union University",
"Virginia University of Science & Technology",
"Virginia Wesleyan University",
"Virginia Western Community College",
"Viterbo University",
"Voorhees College",
"WALSH UNIVERSITY",
"Wabash College",
"Wagner College",
"Wake Forest University",
"Wake Forest University School of Law",
"Wake Technical Community College- Southern Wake Campus",
"Walden University",
"Waldorf University",
"Walla Walla University",
"Wallace State Community College",
"Walsh College",
"Walters State Community College",
"Warren Wilson College",
"Wartburg College",
"Washburn University",
"Washington & Jefferson College",
"Washington Adventist University",
"Washington University in St. Louis",
"Washington World Mission College",
"Washington and Lee University",
"Washtenaw Community College",
"Waubonsee Community College",
"Wayland Baptist University",
"Wayne County Community College District",
"Wayne State College",
"Wayne State University",
"Waynesburg University",
"Weatherford College",
"Webber International University",
"Weber State University",
"Wellesley College",
"Wells College",
"Wenatchee Valley College - Omak",
"Wendell Phillips Academy High School",
"Wentworth Institute of Technology",
"Wesley College",
"Wesleyan University",
"West Chester University of Pennsylvania",
"West Coast University",
"West Hills Community College District",
"West Liberty University",
"West Los Angeles College",
"West Texas A&M University",
"West Valley College",
"West Virginia Northern Community College Wheeling Campus",
"West Virginia State University",
"West Virginia University",
"West Virginia Wesleyan College",
"Westchester Community College",
"Western Carolina University",
"Western Colorado University",
"Western Connecticut State University",
"Western Governors University",
"Western Illinois University",
"Western Illinois University - Quad Cities",
"Western Kentucky University",
"Western Maryland College Historic District",
"Western Michigan University",
"Western Michigan University Thomas M. Cooley Law School",
"Western Nevada College",
"Western New England University",
"Western New Mexico University",
"Western Oregon University",
"Western Washington University",
"Westfield State University",
"Westminster College",
"Westminster Seminary California",
"Westminster Theological Seminary",
"Westmont College",
"Whatcom Community College",
"Wheaton College",
"Wheeling University",
"Whitefield College & Theologic",
"Whitman College",
"Whitworth University",
"Wichita State University",
"Widener University",
"Wilberforce University",
"Wilbur Wright College",
"Wiley College",
"Wilkes University",
"Willamette University",
"William & Mary",
"William Carey University",
"William Howard Taft University",
"William Jessup University",
"William Jewell College",
"William Paterson University",
"William Peace University",
"Williams Baptist University",
"Williams College",
"Wilmington College",
"Wilmington University",
"Wilson College",
"Wingate University",
"Winona State University",
"Winston-Salem State University",
"Winthrop University",
"Wisconsin Lutheran College",
"Wittenberg University",
"Wofford College",
"Woodbury University",
"Wor-Wic Community College",
"Worcester Polytechnic Institute",
"Worcester State University",
"Word of Life Bible Institute",
"Wright State University",
"Wytheville Community College",
"Xavier University",
"Xavier University of Louisiana",
"Yale Divinity School",
"Yale Law School",
"Yale University",
"Yankton College",
"Yavapai College",
"Yeshiva Gedolah College",
"York College",
"York College of Pennsylvania",
"Young Harris College",
"Youngstown State University",
"Ziibiwing Center",
"Zion-Benton Township High School"
    ];
   
    $('#fsCell112356591 > input:eq(0)').attr('id').autocomplete({
    source: availableTags,
      minLength : 3
});
  } );
