 $( function() {
    var availableTags = [
"ABC News",
"ADA University",
"AGH University of Science and Technology",
"AIT - School Of Architecture & Planning",
"Aalborg University",
"Aalto University",
"Aalto University School of Business",
"Aarhus Technical College",
"Aarhus University",
"Abat Oliba CEU University",
"Abat Oliba CEU University (Universitat Abat Oliba CEU)",
"Abia State University",
"Academy Of Arts",
"Academy of Economic Studies of Moldova",
"Acadia University",
"Accra Technical University",
"Addis Ababa University",
"Adelphi University",
"Admiral Makarov National University of Shipbuilding",
"Adventist University of the Philippines",
"Adygey State University",
"Africa University",
"African Bible College (ABC)",
"African Bible University of Uganda",
"African Methodist Episcopal University",
"African Regional Center for Space Science and Technology Education",
"African School of Economics",
"Aga Khan University",
"Agricultural University of Athens",
"AgroParisTech",
"Ahmadu Bello University",
"Aix-Marseille University",
"Ajayi Crowther University",
"Ajou University",
"Akenten Appiah-Menka University of Skills Training and Entrpreneurial Development",
"Akita International University",
"Al Akhawayn University",
"Al Azhar University",
"Al Neelain University",
"Al-Azhar University - Gaza",
"Al-Farabi Kazakh National University",
"Al-Huda International Welfare Foundation",
"Al-Qasemi Academic College of Education",
"AlAqsa University",
"Alagappa University",
"Albanian Institute for International Studies",
"Albanian University",
"Alecu Russo University",
"Aleppo University",
"Algoma University",
"Aligarh Muslim University",
"All Nations University",
"All Saints Cathedral School",
"Allen University",
"Allenby Campus",
"Alpha University College",
"Altai State University",
"Alzahra University.",
"Amani Counselling Centre & Training Institute",
"Ambo University",
"Ambrose University",
"American Graduate School in Paris",
"American Northwest University",
"American Public University System",
"American Samoa Community College",
"American University",
"American University Washington College of Law",
"American University for Humanities",
"American University in Bosnia and Herzegovina",
"American University of Afghanistan",
"American University of Armenia",
"American University of Beirut",
"American University of Central Asia",
"American University of Iraq - Sulaimani (AUIS)",
"American University of Nigeria",
"Amity University Noida",
"Amsterdam University College",
"Anadolu University",
"Anand Academy",
"Andalas University",
"Andrew Jackson University",
"Anglo-American University",
"Arab Academy For Science, Technology & Maritime Transport",
"Arab Academy for Science, Technology & Maritime Transport, Smart Village Campus",
"Arabaev Kyrgyz State University",
"Arba Minch University",
"Aristotle University of Thessaloniki",
"Arizona State University",
"Armenian National Agrarian University",
"Armenian State Pedagogical University",
"Armenian State University of Economics",
"Arts University Bournemouth",
"Asian College of Journalism",
"Asian Institute Of Journalism And Communication",
"Asian Institute of Management",
"Asian Institute of Technology (AIT)",
"Asian School Of Media Studies",
"Asian University for Women",
"Asian University of Bangladesh",
"Asmara Comprehensive Secondary School",
"Assumption University",
"Aston Business School",
"Aston University",
"Astrakhan State Technical University",
"Astrakhan State University",
"Ateneo de Manila University",
"Athabasca University",
"Auckland University of Technology",
"Austin Community College District",
"Australian Catholic University, North Sydney Campus",
"Australian Film Television and Radio School",
"Autonomous University of Asuncion",
"Autonomous University of Baja California",
"Autonomous University of Coahuila (Universidad ...",
"Autonomous University of Madrid",
"Autonomous University of Madrid (Universidad Autónoma de Madrid)",
"Avalon University School of Medicine - Campus",
"Azerbaijan State Economic University",
"Azerbaijan University of Languages",
"B V Bhoomaraddi College Of Engineering & Technology",
"B. Borooah College",
"BI Norwegian Business School - Oslo campus",
"BMT College",
"BSTU, Bryansk State Technical University",
"Baba Farid University of Health Science",
"Babcock University Ilishan Remo",
"Babes-Bolyai University",
"Badji Mokhtar University- Sidi Achour",
"Bahir Dar University peda campus",
"Baku Slavic University",
"Balkh University Old Campus",
"Ballyfermot College of Further Education (Main Building)",
"Balochistan University of Engineering and Technology Khuzdar",
"Banaras Hindu University",
"Bandung Institute of Technology",
"Bangladesh Agricultural University (BAU)",
"Bangladesh University of Engineering and Technology (BUET)",
"Bangor University",
"Bar of Quebec",
"Bar-Ilan University",
"Barcelona Graduate School of Economics",
"Bashkir State University",
"Bath Spa University Newton Park Campus",
"Başkent University",
"Beaconhouse National University Tarogil Campus",
"Beijing Forestry University",
"Beijing Institute of Technology",
"Beijing International Studies University",
"Beijing Language and Culture University",
"Beijing Normal University",
"Beijing Sport University",
"Belarusian National Technical University",
"Belarusian State Economic University",
"Belarusian State Medical University",
"Belarusian State Pedagogical University named after Maxim Tank",
"Belarusian State Technological University",
"Belarusian State University",
"Belarusian State University of Culture and Arts",
"Belfast Metropolitan College - Millfield Campus",
"Belgorod University of Cooperation, Economics and Law",
"Bells University of Technology",
"Ben Gurion University of the Negev",
"Benue State University, Makurdi",
"Berlin Institute of Technology",
"Berlin School of Economics and Law Schöneberg Campus",
"Bharathidasan University",
"Bhavan's College",
"Bielefeld University",
"Bircham International University",
"Birkbeck, University of London",
"Birla Institute of Technology and Science, Pilani",
"Birmingham City University",
"Bishkek Humanitarian University named after K. Karasayeva",
"Bishop's University",
"Blaise Pascal Clermont Ferrand II University",
"Blavatnik School of Government",
"Blekinge Institute of Technology",
"Blida 1 University",
"Board of Intermediate and Secondary Education, Faisalabad",
"Bocconi University",
"Bohdan Khmelnytsjyi National University of Cherkasy",
"Botswana Accountancy College",
"Bournemouth Business School International",
"Bournemouth School",
"Bowen University",
"Brandenburg University of Technology",
"Bratislava International School of Liberal Arts",
"Brest State A.S. Pushkin University",
"Briercrest College and Seminary",
"Brighton & Sussex Medical School",
"British Columbia Institute of Technology",
"British Institute of Technology",
"Brno University of Technology",
"Brock University",
"Brunel University London",
"Bucharest National University of Arts",
"Bucharest University of Economic Studies",
"Buckinghamshire New University",
"Budapest Business School Faculty of Finance and Accountancy",
"Budapest University of Technology and Economics",
"Bugema University",
"Bulgarian Academy of Sciences",
"Burgas Free University",
"Burman University",
"Busoga University",
"CERIS-ULB Diplomatic School of Brussels (CERIS)",
"CEU Cardinal Herrera University",
"CHRIST (Deemed to be University)",
"CUNEF UNIVERSIDAD",
"Cairo University",
"California",
"Cambridge International College, Agona Swedru",
"Cameroon Baptist Theological Seminary",
"Campus De Bizkaia - Campus of Biscay",
"Canadian Mennonite University",
"Cape Breton University",
"Cape Peninsula University of Technology",
"Capilano University",
"Capital University of Economics and Business",
"Cardiff Metropolitan University",
"Cardiff University",
"Cardinal Stefan Wyszyński University in Warsaw",
"Caritas Bianchi College of Careers",
"Caritas University, Amorji-Nike, Enugu",
"Carleton University",
"Cass Business School",
"Catholic University of Central Africa",
"Catholic University of Eastern Africa",
"Catholic University of Eichstaett-Ingolstadt",
"Catholic University of Goiás",
"Catholic University of Paris (Institut catholique de Paris)",
"Catholic University of Petrópolis (Universidade Católica de Petrópolis)",
"Catholic University of Salta",
"Catholic University of Salvador - UCSAL (Universidade Católica do Salvador - UCSal)",
"Catholic University of Santa María (Universidad Católica De Santa Maria)",
"Catholic University of the Sacred Heart",
"Catholic University of the Sacred Heart (Università Cattolica del Sacro Cuore)",
"Católica Porto Business School",
"Caucasus University",
"Cavendish University Uganda",
"Ca’ Foscari University",
"Central European University",
"Central University",
"Central University of Finance and Economics",
"Central University of Gujarat",
"Central University of Haryana",
"Centre for Civil Society",
"Chanakya National Law University",
"Chancellor College of the University of Malawi",
"Charles University",
"Charleston",
"Chartered Insurance Institute",
"Chaudhary Charan Singh University Meerut",
"Chelyabinsk State University",
"Chemnitz University of Technology",
"Chepkoilel University College",
"Cherkasy State Technological University",
"Chernivtsi National University",
"Chhattisgarh Swami Vivekanand Technical University Bhilai",
"Chiba University Nishi-Chiba Campus",
"Chicago",
"Chile",
"China Europe International Business School",
"China Foreign Affairs University",
"China University of Geosciences",
"China University of Petroleum (Huadong)",
"China University of Political Science and Law",
"China Youth University of Political Studies",
"Chongqing University",
"Christian University of North Haiti",
"Chubu University",
"Chulalongkorn University",
"Cihan University",
"City University of Hong Kong",
"City University of Science and Information Technology",
"City, University of London",
"Claude Bernard University Lyon 1",
"College of Europe",
"College of Management Academic Studies",
"College of Medicine, University of Lagos",
"College of Saint Benedict and Saint John's University",
"Collegium Civitas w PKiN",
"Collin County",
"Colorado Northwestern Community College",
"Columbus School of Law The Catholic University of America",
"Communication University of China",
"Community College of Allegheny County",
"Community College of Baltimore County",
"Community College of Rhode Island",
"Complutense University of Madrid",
"Concordia International University",
"Conestoga College Kitchener - Doon Campus",
"Copenhagen Business Academy",
"Copenhagen University",
"Coral Ridge Baptist University",
"Corcoran School of the Arts and Design",
"Corvinus University of Budapest",
"Covenant University",
"Coventry University",
"Cracow University of Economics",
"Craiova University",
"Cranfield University",
"Cuyahoga Community College",
"Cyprus International Institute of Management",
"Czech Academy of Sciences",
"Daegu Arts University",
"Daily Bruin",
"Dal'nevostochnyy Federal'nyy Universitet",
"Dalarna University",
"Dalian Maritime University",
"Damascus University",
"Damelin South Africa",
"Dartford Grammar School",
"Dartington College of Arts",
"Data Link University College",
"Dawson College",
"Daystar University",
"De La Salle University Manila",
"De Montfort University",
"De-General E-Processing Center",
"Deccan College Post Graduate and Research Institute",
"Decebal National College",
"Delaware Technical Community College",
"Delft University of Technology (TU Delft)",
"Delhi School of Economics",
"Delta State University, Abraka",
"Democritus University of Thrace",
"Dhaka Medical College",
"Dhamar University",
"Diego Portales University",
"Dimitrie Cantemir Christian University",
"Diplomatic Academy of Vienna",
"Diplomatic Academy of Vietnam",
"Dokkyo University",
"Don State Technical University",
"Donbas National Academy of Civil Engineering and Architecture",
"Donbass State Technical University",
"Donetsk National University",
"Donetsk State University of Management",
"Dongbei University of Finance and Economics",
"Donghua University",
"Douglas College New Westminster Campus",
"Dr B R Ambedkar National Institute of Technology Jalandhar",
"Dr. Bhimrao Ambedkar University",
"Dr. M.G.R. Educational And Research Institute",
"Dr. Ram Manohar Lohia Avadh University, Ayodhya",
"Drahomanov National Pedagogical University",
"Dresden University of Technology",
"Dronacharya College of Engineering",
"Dschang University",
"Dublin Business School",
"Dublin City University",
"Durban University of Technology",
"Durham University",
"E-Library Kano State Polytechnic",
"ESAN University (Universidad ESAN)",
"ESC Rennes School of Business (Rennes School of Business)",
"ESCP Business School",
"ESRA - ISTS - Sup'Infograph Paris",
"Earth University",
"East African Media Institute",
"East China Normal University",
"East China University of Political Science and Law",
"East China University of Science and Technology",
"East Institute of Puebla (Instituto Oriente)",
"Eastern Mediterranean University",
"Eberhard Karls University of Tübingen",
"Ecological University of Bucharest",
"Edinburgh Napier University",
"El Paso Community College",
"Embry–Riddle Aeronautical University",
"Emily Carr University of Art + Design",
"Enugu State University of Science and Technology",
"Erbil Polytechnic University",
"Estonian Business School",
"Estonian School of Diplomacy",
"European Humanities University",
"European Peace University",
"European University",
"European University At St Petersburg",
"European University Institute",
"European University of Lefke",
"Evelyn Hone College of Applied Arts and Commerce",
"Ewha Womans University",
"FAST NUCES Lahore",
"FEBIAS College of Bible",
"FGV - Getulio Vargas Foundation",
"FIEO University Centre",
"Faculty of Law of the University of Zagreb",
"Fanshawe College",
"Fatima Jinnah Women University",
"Federal Univeristy Of Agriculture Makurdi",
"Federal University of ABC, Campus Santo André",
"Federal University of Agriculture, Abeokuta",
"Federal University of Bahia Ondina Campus (Universidade Federal da Bahia Campus Ondina)",
"Federal University of Lavras",
"Federal University of Minas Gerais",
"Federal University of Minas Gerais (Universidade Federal de Minas Gerais)",
"Federal University of Ouro Preto (Universidade Federal de Ouro Preto)",
"Federal University of Parana",
"Federal University of Paraíba",
"Federal University of Pelotas (Universidade Federal de Pelotas)",
"Federal University of Pernambuco UFPE",
"Federal University of Rio Grande do Sul",
"Federal University of Santa Maria",
"Federal University of Technology Akure",
"Federal University of Viçosa (UFV)",
"Federal Urdu University of Arts, Sciences & Technology",
"Federal university of technology minna",
"Federico Villarreal National University",
"Ferdowsi University Mashhad",
"Fergana State University",
"Fidélitas University",
"Film and Television Institute of India",
"Financial University under the Government of the Russian Federation",
"Florida Technical College",
"Foreign Trade University",
"Forman Christian College (A Chartered University)",
"Fort Smith",
"Foundation for Economic Education",
"Fourah Bay College",
"Free International University of Moldova",
"Free university of Tbilisi",
"Freetown Secondary School for Girls (FSSG)",
"From Ngaoundere University",
"Fudan University",
"Gallaudet University",
"Garden City University College",
"Gauhati University",
"Gdańsk University of Technology",
"Geneva University of Music",
"George C. Marshall European Center for Security Studies",
"Georgetown",
"Georgetown University",
"Georgetown University Law Center",
"Georgetown University McDonough School of Business",
"Georgetown University School-Medicine",
"Georgian Institute of Public Affairs (GIPA)",
"Georgian Technical University",
"German Jordanian University",
"Germanna Community College",
"Ghana Communication Technology University",
"Ghana Institute of Management and Public Administration (GIMPA)",
"Ghent University",
"Ghulam Ishaq Khan Institute of Engineering Sciences and Technology",
"Global Center for Advanced Studies",
"Goa Institute Of Management",
"Goethe University Frankfurt",
"Goethe University Frankfurt (Goethe-Universität Frankfurt am Main)",
"Gokhale Institute of Politics and Economics, Pune",
"Goldsmiths, University of London",
"Gothenburg University",
"Government College Ibadan",
"Government College University Faisalabad",
"Government Technical College Agidingbi",
"Graduate School of Management in Barcelona",
"Graduate School of Management-Abidjan",
"Graffins College",
"Graz University of Technology",
"Great Lakes University",
"Griffith University",
"Guildford School of Acting",
"Gujarat National Law University",
"Gujarat Technological University",
"Gulistan State University",
"Guru Gobind Singh Indraprastha University",
"H.S. Skovoroda Kharkiv National Pedagogical University",
"HELP University",
"HafenCity University Hamburg (HCU)",
"Haigazian University",
"Hanken School of Economics",
"Hankuk University of Foreign Studies Seoul Campus",
"Hannam University",
"Hanoi National University of Education",
"Hanoi University",
"Haramaya University",
"Harbin Institute of Technology",
"Harvard University",
"Hasselt University",
"Hawassa University",
"Hebron University, Palestine",
"Heilongjiang University",
"Hekima University College Institute Of Peace Studies and International Relations",
"Herat University- دانشگاه هرات",
"Heriot-Watt University, Edinburgh Campus",
"HiLCoE School of Computer Science and Technology",
"High school in the United States",
"Higher School of Economics",
"Hindusthan College of Arts & Science",
"Ho Technical University",
"Holy Spirit University of Kaslik - Lebanese Maronite Order",
"Hong Kong University of Science and Technology",
"Hope Africa University",
"Howard University",
"Huazhong University of Science and Technology",
"Hugh Wooding Law School",
"Hult International Business School",
"Humanity First Institute of Information Technology",
"Humboldt University of Berlin",
"Hunan University",
"Hungarian Academy of Sciences",
"Hyperion University",
"I. K. Gujral Punjab Technical University",
"IBB University , Lapai",
"ICARE Foundation, Agribusiness Teaching Center, EVN Wine Academy",
"IE Business School",
"IE University",
"ILCS Institute for Leadership and Communication Studies",
"ILS Law College",
"IMC University of Applied Sciences Krems",
"IMD Business School",
"IMI International Management Institute",
"IMSR Institute - Distance MBA",
"IMT School for Advanced Studies Lucca",
"ISCTE - Lisbon University Institute",
"ISM University of Management and Economics",
"IVRI Deemed University",
"Ibmec RJ - Faculty, Graduate and MBA",
"Ibn Tofail University",
"Igbinedion University Okada",
"Ilia State University",
"Ilmenau University of Technology",
"Imo State University",
"Indian Institute Of Journalism & New Media",
"Indian Institute of Information Technology, Design and Manufacturing, Kancheepuram",
"Indian Institute of Management Ahmedabad",
"Indian Institute of Science",
"Indian Institute of Technology Bombay",
"Indian Institute of Technology Delhi",
"Indian Institute of Technology Guwahati",
"Indian Institute of Technology Kanpur",
"Indian Institute of Technology Kharagpur",
"Indian Institute of Technology Roorkee",
"Indian Institute of Technology, Jodhpur",
"Indian Institute of Technology, Mandi",
"Indian Ocean University",
"Indian Statistical Institute",
"Indira Gandhi National Open University - Head Office",
"Indonesia Open University (UT)",
"Indonesian Institute Of The Arts",
"Industrial University of Santander (Universidad Industrial de Santander)",
"Industryinfinitymillennials",
"Inland Norway University of Applied Sciences, Lillehammer",
"Innovation Campus - UBT",
"Institute Of Advanced Management & Technology",
"Institute Of Chartered Financial Analysts Of India",
"Institute for Advanced Studies",
"Institute for Science and International Security",
"Institute of Accounting and Administration",
"Institute of Accounting and Commerce",
"Institute of Advanced Studies in Education",
"Institute of Business Administration, Karachi",
"Institute of Business Management",
"Institute of Ecumenical Education",
"Institute of Finance Management (IFM)",
"Institute of Higher Education No. 28 \"Olga Cossettini\"",
"Institute of Management and Technology",
"Institute of Public Administration",
"Institute of Rural Development Planning",
"Intec College",
"International Academy of Design and Technology",
"International Academy of Film and Television - Cebu",
"International Academy of Philosophy",
"International Alatoo University",
"International Black Sea University",
"International People's College",
"International Society for Performance Improvement",
"International University College of Turin",
"International University in Geneva",
"International University of Japan",
"Ion Mincu University of Architecture and Urbanism",
"Islamic Azad University",
"Islamic University College, Ghana",
"Islamic University in Uganda",
"Islamic University of Gaza",
"Istanbul University",
"Ivan Franko National University of Lviv",
"Ivane Javakhishvili Tbilisi State University",
"J. F. Oberlin University",
"JMJ Homes",
"Jacobs University Bremen",
"Jadavpur University",
"Jagiellonian University",
"Jakarta Institute of Arts (INSTITUT KESENIAN JAKARTA)",
"Jalal-Abad State University",
"Japan International Cooperation Agency",
"Jaume I University",
"Jawaharlal Nehru Architecture and Fine Arts University",
"Jawaharlal Nehru Centre For Advanced Scientific Research",
"Jawaharlal Nehru Technological University Hyderabad",
"Jerusalem University College",
"Jesus and Mary College",
"Jiangsu University",
"Jiangxi University of Finance and Economics",
"Jimma University",
"Johannes Gutenberg University of Mainz",
"John Cabot University Guarini Campus",
"Johns Hopkins University School of Advanced International Studies",
"Joliet Junior College",
"Jomo Kenyatta University Of Agriculture And Technology",
"Jones International University",
"Jordan University of Science and Technology",
"Jowor Schools",
"Jusup Balasagyn Kyrgyz State University",
"K J Somaiya Institute of Management",
"KAIPTC - Kofi Annan International Peacekeeping Training Centre",
"KDI School of Public Policy and Management",
"KEDGE Business School - Campus Luminy",
"KIMEP University",
"Kabul University",
"Kainan University",
"Kalinga Institute of Industrial Technology",
"Kaliningrad State Technical University",
"Kampala International University in Tanzania (KIUT)",
"Kaplan University",
"Karadeniz Technical University",
"Karagandy State University",
"Karakoram International University",
"Kazakh Ablai Khan University of International Relations and World Languages",
"Kazakh National University of the Arts",
"Kazan Federal University",
"Keele University",
"Kennesaw State University",
"Kenya College Of Commerce And Hospitality",
"Kenya Institute Of Special Education",
"Kenya Institute of Mass Communication",
"Kenya Methodist University Nairobi Campus",
"Kenya School Of Law",
"Kenya Technical Trainers College (KTTC",
"Khabarovsk State University of Economics and Law",
"Kharazmi University, Tehran Campus",
"Kharkiv Institute of Banking",
"Kharkiv National University of Economics",
"Khazar University",
"Kherson National Technical University",
"Khorog State University",
"Khujand Polytechnic Institute of Tajik Technical University",
"Khujand State University",
"Kigali Independent University",
"King Abdulaziz University",
"King Abdullah University of Science and Technology",
"King's College London",
"King's University College",
"Kinnaird College For Women University",
"Klaipeda University",
"Koc University",
"Koc University (Koç Üniversitesi)",
"Kocaeli University",
"Koforidua Technical University",
"Korea Development Institute",
"Korea University",
"Kostanay State University",
"Kristianstad University",
"Kryvyi Rih Economic Institute",
"Kuban State Agrarian University",
"Kuban State University",
"Kwame Nkrumah University of Science and Technology",
"Kwantlen Polytechnic University",
"Kwara State College of Education, Ilorin",
"Kyambogo University",
"Kyiv International University",
"Kyiv National Economic University",
"Kyiv National Linguistic University",
"Kyoto University",
"Kyrgyz Russian Slavic University",
"Kyrgyz State Law Academy",
"Kyung Hee University",
"Kyungwon University",
"Kyushu University",
"LCC International University",
"LUMS - Lahore University of Management Sciences",
"La Trobe University Melbourne Campus",
"Lackawanna County",
"Lagos City Computer College, Ikeja",
"Lagos State University",
"Lahore College for Women University",
"Lalbhai Dalpatbhai College of Engineering",
"Lancaster University",
"Laureate Education",
"Laval University",
"Law School Milton Campos Cefos",
"Lead City University",
"Lebanese University, Hadat Campus",
"Lebanon County",
"Leeds Beckett University",
"Lesya Ukrainka Eastern European National University",
"Leuphana University of Lüneburg",
"Liaoning Normal University",
"LimKokWing University",
"Lincoln University",
"Lingnan University",
"Linnaeus University",
"Lisbon (Lisboa)",
"Lithuanian Academy of Music and Theatre",
"Liverpool Hope University - Hope Park Campus",
"London Film School",
"London Guildhall College",
"London School of Economics and Political Science",
"London School of Public Relations Jakarta Campus A now is LSPR Communication & Business Institute located in Sudirman Park Campus Jakarta, Transpark Juanda Campus Bekasi, and Renon Campus Bali.",
"London South Bank University",
"London Teacher Training College",
"Loughborough University",
"Lucian Blaga University of Sibiu",
"Ludwig Maximilian University of Munich",
"Luhansk State University of Internal Affairs",
"Luleå University of Technology",
"Lund University",
"Lviv University of Trade and Economics",
"Lycoming County",
"Lyon 2 University Berges du Rhone Campus",
"MVJ College of Engineering",
"Maastricht School of Management",
"Maastricht University",
"Macquarie University",
"Madonna University Nigeria",
"Magadh University",
"Maharashtra Institute Of Technology",
"Maharashtra University of Health Sciences",
"Maharshi Dayanand University",
"Mahatma Gandhi University",
"Mahidol University International College-MUIC",
"Maikop State Technological University",
"Makerere Institute of Social Research (MISR)",
"Malawi Institute of Journalism - Blantyre Campus",
"Malek Ashtar University of Technology",
"Management Development Institute of Singapore in Tashkent",
"Manchester Metropolitan University",
"Manipal Academy of Higher Education",
"Manohar Parrikar Institute for Defence Studies and Analyses (MP-IDSA)",
"Manouba University",
"Marien Ngouabi University",
"Marmara University",
"Marmara University Dragos Campus",
"Martin-Luther-University Halle-Wittenberg",
"Mary Immaculate College",
"Masaryk University",
"Maseno University-Kisumu Campus",
"Masinde Muliro University of Science and Technology",
"Massey University",
"Maulana Abul Kalam Azad University of Technology, West Bengal",
"Maulana Azad National Institute of Technology",
"Maynooth University",
"Mayo Clinic Graduate School of Biomedical Sciences",
"Mbarara University Of Science And Technology",
"McGill University",
"McMaster University",
"Mediterranean Agronomic Institute of Chania",
"Mehran University of Engineering and Technology",
"Memorial University of Newfoundland",
"Mendel University in Brno",
"Meritorious Autonomous University of Puebla (...",
"Methodist University of São Paulo",
"Metropolitan University Prague",
"Michigan State University",
"Midlands State University",
"Military Engineering Institute (IME) (Instituto Militar de Engenharia (IME))",
"Milton Margai College Of Education and Technology - Goderich Campus",
"Mindanao State University - Iligan Institute of Technology",
"Ministry of Justice of the Russian Federation",
"Minsk State Linguistic University",
"Mirpur University of Science and Technology (MUST)",
"Mizan - Tepi University",
"Mogadishu University",
"Mohammed V University",
"Mohawk College",
"Moldova State University",
"Monash College City Campus",
"Monash University Clayton Campus",
"Mongolian National University of Medical Sciences",
"Mongolian State University of Education",
"Monroe Community College",
"Montego Bay Community College",
"Montgomery County",
"Montmorency College",
"Montsaye Academy",
"Moscow Aviation Institute",
"Moscow Engineering Physics Institute",
"Moscow Polytechnic University",
"Moscow State Academy of Water Transport",
"Moscow State Institute of International Relations",
"Moscow State Linguistic University",
"Moscow State University",
"Mount Allison University",
"Mount Carmel College Autonomous",
"Mount Kenya University Sacco Society",
"Mount Meru University",
"Mount Royal University",
"Mount Saint Vincent University",
"Multi Media University",
"Multimedia University - MMU Cyberjaya",
"Mulungushi University, Town Campus",
"Murmansk State Humanities University",
"Mutah University",
"Mykolas Romeris University",
"Mzumbe University",
"NAIROBI AVIATION COLLEGE, HEAD OFFICE",
"NATIONAL MEDICAL UNIVERSITY NAMED AFTER OO WORSHIPERS",
"NIBS-[Nairobi Institute of Business Studies] NAIROBI CAMPUS",
"NMIMS Deemed-to-be-University",
"Nagoya University",
"Namibia University of Science and Technology (NUST)",
"Nanjing Normal University",
"Nanjing University",
"Nankai University",
"Narcotics Anonymous",
"National Academy of Public Administration",
"National Academy of Sciences of Ukraine",
"National Archives of India",
"National Autonomous University of Mexico",
"National Aviation University",
"National Center For Biological Sciences",
"National Cheng Kung University",
"National Chengchi University",
"National Conservatory of Arts and Crafts",
"National Defence University",
"National Defense University",
"National Dong Hwa University",
"National Economics University (NEU)",
"National Film and Television School (NFTS)",
"National High School of Humanities and Arts "Konstantin Preslavski"",
"National Institute of Education (NIE), Singapore",
"National Institute of Fashion Technology",
"National Institute of Technology, Rourkela",
"National Law Institute University",
"National Law School of India University",
"National Law University, Delhi",
"National Law University, Odisha",
"National Metallurgical Academy Of Ukraine",
"National Open University (Universidad Nacional Abierta (UNA))",
"National School of Political and Administrative Studies SNSPA",
"National Taiwan Normal University",
"National Taiwan University",
"National University Of Modern Languages",
"National University of Costa Rica",
"National University of Ireland",
"National University of Ireland, Galway",
"National University of La Plata",
"National University of Lesotho",
"National University of Mongolia",
"National University of Quilmes (Universidad Nacional de Quilmes)",
"National University of Rosario: Government Headquarters",
"National University of Rosario: Government Headquarters (Universidad Nacional de Rosario: Sede de Gobierno)",
"National University of San Marcos",
"National University of Theatre and Film "I.L. Caragiale" in Bucharest",
"National University, Bangladesh",
"National and Kapodistrian University of Athens",
"Naval School",
"Nazarbayev University",
"Negros Oriental State University - Main Campus",
"Nelson Mandela University",
"Netherlands-Thai Chamber of Commerce",
"New Bulgarian University",
"New Era University",
"New Generation University College",
"New Image College",
"New Jersey",
"New Sorbonne University Paris 3",
"New University Campus Agadir",
"New York",
"New York City Department of Environmental ...",
"Newbold College of Higher Education",
"Newcastle University",
"Nicolaus Copernicus University",
"Nizhyn Gogol State University",
"Njala University Campus",
"Nkumba University",
"Nnamdi Azikiwe University",
"Nordakademie University of Applied Sciences",
"North-Eastern Hill University",
"Northern Caribbean University",
"Northern University",
"Northumbria University",
"Northwest A&F University",
"Norwegian University of Life Sciences NMBU",
"Notre Dame University College",
"Nottingham College Adams Building",
"Nova School of Business and Economics",
"Novosibirsk State University",
"Nuclear Power School",
"Nuffield College, University of Oxford",
"Nwataeze Royal structures and interior",
"O.P. Jindal Global University",
"OCAD University",
"Oakland Community College",
"Obafemi Awolowo University",
"Ocean University of China",
"Ochanomizu University",
"Odesa National Medical University",
"Odesa State Economic University",
"Oklahoma State University",
"Oles Honchar Dnipro National University",
"Omdurman Ahlia University",
"Omsk State Technical University",
"Open International University of Human Development \"Ukraine\"",
"Open Universities Australia",
"Open University Malaysia",
"Orta Doğu Teknik Universitesi Middle East Technical University",
"Osgoode Hall Law School",
"Osmania University",
"Osnabrück University of Applied Sciences",
"Osun State Polytechnic Iree",
"Osun State University",
"Otto von Guericke University Magdeburg",
"Otto-Friedrich-University Bamberg",
"Oxford Brookes University Headington Campus",
"POLITEHNICA University of Bucharest",
"PSG College Of Technology",
"Padang State University",
"Pan African Online School Of Forex (PAOSOFX)",
"Pan-Atlantic University",
"Pandit Deendayal Energy University- PDEU (Formerly PDPU)",
"Pantheon-Sorbonne University",
"Panthéon-Assas University Paris II",
"Paramadina University",
"Paris Dauphine University",
"Paris Diderot University",
"Paris Graduate School Of Management",
"Paris Nanterre University",
"Paris Nanterre University (Université Paris Nanterre)",
"Paris School of Economics",
"Paris-Sorbonne University",
"Payame Noor University",
"Payap University",
"Peking University",
"Peoples' Friendship University of Russia",
"Perimeter College at Georgia State University",
"Petro Mohyla Black Sea National University",
"Philippine Christian University",
"Philippine Normal University",
"Philipps-University Marburg",
"Pir Mehr Ali Shah Arid Agriculture University - PMAS AAUR",
"Pokhara University",
"Polish Institute of International Affairs",
"Polytech Clermont",
"Polytechnic University of Madrid",
"Polytechnic University of Milan",
"Polytechnic University of Turin",
"Pompeu Fabra University",
"Pondicherry University",
"Pontifical Bolivarian University",
"Pontifical Catholic University of Ecuador",
"Pontifical Catholic University of Minas Gerais",
"Pontifical Catholic University of Paraná, Curitiba Campus",
"Pontifical Catholic University of Peru",
"Pontifical Catholic University of Peru (Pontificia Universidad Católica del Perú)",
"Pontifical Catholic University of Rio Grande do Sul",
"Pontifical Catholic University of Rio de Janeiro (PUC-Rio)",
"Pontifical Catholic University of São Paulo (PUC-SP - Campus Monte Alegre (Perdizes))",
"Pontifical Catholic University of Valparaíso (Pontificia Universidad Católica de Valparaíso)",
"Pontifical Lateran University",
"Pontifical University of St. Thomas Aquinas - Angelicum",
"Porto Business School",
"Post Graduate Institute of Medical Education & Research, Chandigarh",
"Postgraduate School of Nusa Cendana University",
"Poznań University of Technology",
"Prague University of Economics and Business",
"Presidency University",
"Presidency of the University of Nouakchott",
"Prifysgol Aberystwyth University, Penglais Campus",
"Private Universidad San Pablo CEU",
"Professionals' Academy of Commerce",
"Protestant University of The Congo",
"Pryazovskyi State Technical University",
"Pukyong National University Daeyeon Campus",
"Puntland State University",
"Pusan National University",
"Pułtusk Academy of Humanities",
"Pwani University",
"Qatar University",
"Qazvin Islamic Azad University",
"Quaid-i-Azam University Islamabad",
"Queen Mary University of London",
"Queen's University",
"Queen's University Belfast",
"Quest University Canada",
"Quirino State University, Main Campus,",
"RMIT University Melbourne City Campus",
"RNTC - Radio Netherlands Training Centre",
"Rabindra Bharati University",
"Radboud University Nijmegen",
"Rajarata University of Sri Lanka",
"Ramon Llull University",
"Rectorate of the University of Belgrade",
"Regent's University London",
"Regional Maritime University",
"Regional Municipality of Niagara",
"Rey Juan Carlos University",
"Rhodes University",
"Rift Valley University",
"Riga Graduate School of Law",
"Riga Stradins University",
"Rio de Janeiro State University",
"Ritsumeikan Asia Pacific University",
"Robert Gordon University",
"Romanian-American University",
"Rostov State University of Economics",
"Rothberg International School",
"Rowan College at Burlington County",
"Royal College of Surgeons in Ireland",
"Royal Military College of Canada",
"Rural Federal University of Rio de Janeiro",
"Russian Academy of Public Administration",
"Russian Academy of Sciences",
"Russian State Social University",
"Russian State University for the Humanities",
"Russian-Armenian University",
"Russian-Tajik Slavonic University",
"Ryazan State University named after SA Yesenin",
"Ryerson University",
"Ryukyu University No. 1 Gymnasium",
"SAE Institute Byron Bay",
"SBS Swiss Business School",
"SKANS School of Accountancy",
"SNDT Women's University",
"SOAS University of London",
"Saarland University",
"Sabancı University",
"Saint Mary's University",
"Saint Petersburg Electrotechnical University",
"Saint Petersburg State University",
"Saint Petersburg State University of Aerospace Instrumentation",
"Saint Stephen's Early Learning Centre",
"Samara University",
"San Carlos University",
"San Sebastian College – Recoletos",
"Sana'a University",
"Sangmyung University, Seoul Campus",
"Sanjay Gandhi Postgraduate Institute of Medical Sciences",
"Sant Gadge Baba Amravati University",
"Sapienza University of Rome",
"Savannah State University",
"Saxion University",
"School Suger",
"Sciences Po Strasbourg",
"Sebelas Maret University (Universitas Sebelas Maret)",
"See results about",
"Semey State Medical University",
"Seminole County",
"Seoul National University",
"Shah Abdul Latif University, Khairpur",
"Shaheed Zulfikar Ali Bhutto Institute of Science & Technology",
"Shaheed Zulfikar Ali Bhutto Institute of Science and Technology - Karachi Campus",
"Shahid Bahonar University of Kerman",
"Shahjalal University of Science and Technology",
"Shanghai International Studies University",
"Shanghai Jiao Tong University",
"Shanghai Normal University",
"Shanghai University of Finance and Economics",
"Shanto-Mariam University of Creative Technology",
"Sheridan College Trafalgar Road Campus",
"Shirak State University",
"Shiraz University",
"Shota Meskhia State Teaching University of Zugdidi",
"Shri Ram College of Commerce",
"Siberian University of Consumer Cooperatives",
"Sies College Of Arts, Science & Commerce",
"Sikkim Manipal University",
"Silsoe Research Institute",
"Simon Bolivar Andean University",
"Simon Fraser University",
"Simpson University",
"Sims College Of Physiotherapy",
"Sir Syed CASE Institute of Technology",
"Sofia University",
"Somali National University",
"Sophia College",
"Sophia Polytechnic College",
"Sophia University",
"Sorbonne University Pierre and Marie Curie Campus",
"South Asian University",
"South China Agricultural University",
"South China University of Technology",
"South East European University",
"South Kamloops Secondary School",
"South Mediterranean University (MSB-MEDTECH-LCI)",
"South University",
"South-West University \"Neofit Rilski\"",
"Southern Alberta Institute of Technology",
"Southern Cross University",
"Southern New England School of Law",
"Southwark College",
"Southwest University",
"Southwestern University of Finance and Economics",
"Spicer Adventist University",
"Sri Lanka Institute of Information Technology",
"Ss. Cyril and Methodius University",
"St Aloysius' College",
"St Antony's College",
"St. Anthony Village High School",
"St. Clair College - Chatham Campus",
"St. Francis Xavier University",
"St. George's University",
"St. Mary's College Kisubi",
"St. Paul's University",
"St. Thomas University",
"St.John's University of Tanzania",
"Star College of Management Studies",
"State University of Management",
"State University of New York System",
"State University of Nizhny Novgorod",
"State University «Odessa Polytechnic»",
"Stevenson University",
"Stockholm School of Economics",
"Strasbourg University",
"Stratford College of Business and Management",
"Strathmore University",
"Sun Yat-sen University",
"Suresh Gyan Vihar University",
"Swansea University",
"Swedish University of Agricultural Sciences",
"Swinburne University of Technology",
"Swiss German University The Prominence Tower Campus",
"Sydney Film School",
"Syracuse University",
"Süleyman Demirel University",
"T.A. Marryshow Community College",
"TERI School Of Advanced Studies",
"TIET - Thapar Institute of Engineering And Technology",
"TOBB University of Economics and Technology",
"Tai Solarin University Of Education .",
"Tajik National University",
"Takoradi Technical University",
"TalTech – Tallinn University of Technology",
"Tangaza University College",
"Tansian University",
"Taras Shevchenko National University of Kyiv",
"Tarbiat Modares University",
"Tarsus American College",
"Tashkent Institute of Design, Construction & Maintenance of Automotive Roads",
"Tashkent State Institute of Oriental Studies",
"Tata Institute of Social Sciences",
"Tavria State Agrotechnological University",
"Tavrida National V.I. Vernadsky University",
"Technical Education, Vocational and Entrepreneurship Training Authority",
"Technical University Dortmund",
"Technical University of Applied Sciences Lübeck",
"Technical University of Denmark",
"Technical University of Liberec",
"Technical University of Lisbon",
"Technical University of Mombasa",
"Technological Institute",
"Technological University of Chocó (Universidad Tecnológica Del Chocó)",
"Technological University of the Philippines - Manila",
"Teesside University",
"Tehran Conservatory Of Music",
"Ternopilʹsʹkyy Natsionalʹnyy Tekhnichnyy Universytet Imeni Ivana Pulyuya",
"Thammasat University",
"The Academy Of Public Administration Under The President Of The Republic Of Azerbaijan",
"The Aga Khan Academy, Mombasa",
"The American Business School of Paris",
"The American College of Greece",
"The American University in Cairo",
"The American University in Kosovo",
"The American University of Paris",
"The American University of Rome",
"The Arab Academy for Management, Banking and Financial Sciences (AAMBFS)",
"The Australian National University",
"The Bahamas",
"The British University in Egypt",
"The Catholic University of America",
"The Centre for Studies in Social Sciences, Calcutta",
"The Chinese University of Hong Kong",
"The Citadel",
"The City of Liverpool College",
"The College of Mexico A.C.",
"The Federal Polytechnic Ede",
"The Gandhigram Rural Institute-Deemed to be University",
"The George Washington University",
"The George Washington University Law School",
"The Glasgow School of Art",
"The Graduate Institute, Geneva (IHEID)",
"The Hague Academy of International Law",
"The Hague University of Applied Sciences",
"The Hashemite University",
"The Hebrew University of Jerusalem",
"The Hong Kong Polytechnic University",
"The Institute of Ismaili Studies",
"The Institute of World Politics",
"The John Paul II Catholic University of Lublin",
"The London School of Journalism",
"The Maharaja Sayajirao University of Baroda",
"The National Pedagogical University named after Abai",
"The Nigerian Law School",
"The Open University",
"The Technical University of Moldova",
"The Uganda Institute Of Banking and Financial Services",
"The Umbra Institute",
"The University of Auckland",
"The University of British Columbia",
"The University of British Columbia Okanagan Campus",
"The University of Buckingham",
"The University of Edinburgh",
"The University of Guyana",
"The University of Haripur",
"The University of Hong Kong",
"The University of Jordan",
"The University of Manchester",
"The University of Sydney",
"The University of Tokyo",
"The University of Winnipeg",
"The University of Zambia",
"The University of the West Indies - St. Augustine Campus",
"The Washington Center",
"The World Islamic Sciences and Education University",
"Tianjin University",
"Tidewater Community College",
"Tilburg University",
"Tishreen University",
"Tohoku University",
"Tokai University Yoyogi Campus",
"Tolani College of Commerce",
"Torcuato Di Tella University: School of Business",
"Toulouse Business School",
"Toulouse School of Economics",
"Trans Africa University College",
"Transilvania University",
"Trent University",
"Tribhuvan University",
"Trinity Tigers",
"Trinity Western University",
"Tshwane University of Technology",
"Tsuda University Kodaira Campus",
"Tunghai University",
"Tunis University",
"Tyumen State Academy of World Economics, Management and Law",
"Tyumen State University",
"U.S. Institute of Peace",
"UAC Health Sciences Faculty",
"UNIA - University of Seville",
"UNIVERSITE DU LAC TANGANYIKA",
"UWC Atlantic College",
"UWC Red Cross Nordic",
"Ufimskiy Gosudarstvennyy Aviatsionnyy Tekhnicheskiy Universitet",
"Uganda Christian University Mukono",
"Uganda Institute of Business and Media Studies",
"Uganda Martyrs University Nkozi",
"Uganda National Entrepreneurship Development Institute",
"Ukrainian Catholic University",
"Ulm University",
"UniBH - Campus Buritis",
"Unitec Institute of Technology, Mt Albert Campus Map",
"United Metropolitan Colleges",
"United Nations Interregional Crime and Justice Research Institute",
"United Nations University",
"United States Air Force",
"United States Air Force Academy",
"United States Military Academy",
"Unity University ዩኒቲ ዩኒቨርሲቲ",
"Universidad Finis Terrae",
"Universidad ORT Uruguay (Campus Center)",
"Universidad de Lubumbashi",
"Universite Cheikh Anta Diop (UCAD)",
"University Carlos III of Madrid | Getafe Campus",
"University Centre of Curitiba",
"University College Cork",
"University College Dublin",
"University College London",
"University College of Cundinamarca (Universidad Colegio Mayor De Cundinamarca)",
"University College of Management Studies",
"University De Sousse",
"University Law College, P.U",
"University Of Balochistan",
"University Of Cape Coast",
"University Of Dar Es Salaam",
"University Of Jos, Main Campus",
"University Of Kassala",
"University Of Mysore (UoM)",
"University Of Patras",
"University Of Uyo",
"University Paris 8",
"University Polytechnic Hauts-de-France",
"University for Development Studies",
"University for Information Science and Technology \"St. Paul the Apostle\"",
"University of A Coruña (Universidade da Corunha)",
"University of Agder",
"University of Agriculture, Peshawar",
"University of Alicante",
"University of Angers",
"University of Antananarivo",
"University of Antwerp",
"University of Applied Arts Vienna",
"University of Arts and Social Sciences Arcis (Universidad de Artes y Ciencias Sociales Arcis)",
"University of Asia and the Pacific (UAP)",
"University of Asmara",
"University of Aveiro",
"University of Baghdad",
"University of Banja Luka",
"University of Barcelona",
"University of Basel",
"University of Bayreuth",
"University of Bedfordshire",
"University of Beira Interior (Universidade Beira Interior)",
"University of Belgrade Faculty of Philosophy",
"University of Belgrade Faculty of Political Science",
"University of Benin",
"University of Bergen",
"University of Bern",
"University of Birmingham",
"University of Bogota Jorge Tadeo Lozano",
"University of Bolton",
"University of Bonn",
"University of Botswana",
"University of Bradford",
"University of Brasília",
"University of Brighton",
"University of Bristol",
"University of Bucharest",
"University of Buenos Aires",
"University of Burgundy",
"University of Burundi",
"University of Calabar, Calabar",
"University of Calabria",
"University of Calcutta",
"University of Calgary",
"University of Calicut",
"University of California",
"University of California, Berkeley",
"University of Cambridge",
"University of Canberra",
"University of Cantabria",
"University of Cape Town",
"University of Carabobo",
"University of Central Asia Khorog Campus",
"University of Central Lancashire",
"University of Chester Exton Park Campus",
"University of Chittagong",
"University of Coimbra",
"University of Cologne",
"University of Curaçao Dr. Moises Da Costa Gomez",
"University of Delhi",
"University of Derby",
"University of Deusto",
"University of Deusto (Universidad de Deusto)",
"University of Development Alternative",
"University of Dhaka",
"University of Divinity",
"University of Dodoma",
"University of Donja Gorica",
"University of Douala",
"University of Dundee",
"University of East Anglia",
"University of East London",
"University of Economics Ho Chi Minh City - UEH",
"University of Education, Lahore",
"University of Erfurt",
"University of Erfurt (Universität Erfurt)",
"University of Erlangen-Nuremberg",
"University of Essex Colchester Campus",
"University of Europe for Applied Sciences (Campus Hamburg)",
"University of Exeter",
"University of Extremadura (Universidad de Extremadura)",
"University of Ferrara",
"University of Flensburg",
"University of Freiburg",
"University of Fribourg",
"University of Ghana",
"University of Giessen",
"University of Glasgow",
"University of Gloucestershire",
"University of Goma",
"University of Gondar",
"University of Graz",
"University of Greenwich",
"University of Groningen",
"University of Guadalajara",
"University of Guilan",
"University of Göttingen",
"University of Haifa",
"University of Helsinki",
"University of Hertfordshire de Havilland Campus",
"University of Hohenheim",
"University of Huddersfield Queensgate Campus",
"University of Hull",
"University of Hyderabad",
"University of Ibadan",
"University of Illinois at Urbana-Champaign",
"University of Ilorin",
"University of Innsbruck",
"University of Insubria",
"University of International Relations",
"University of Jember (Universitas Jember)",
"University of Jena",
"University of Jijel",
"University of Johannesburg",
"University of Kaiserslautern",
"University of Kalamoon",
"University of Kalyani",
"University of Kashmir",
"University of Kelaniya - Sri Lanka",
"University of Kent",
"University of Kerala",
"University of Khartoum",
"University of King's College",
"University of Koblenz and Landau",
"University of Konstanz",
"University of Kufa",
"University of Kurdistan Hewler (UKH)",
"University of KwaZulu-Natal",
"University of La Laguna",
"University of Lausanne",
"University of Law",
"University of Leeds",
"University of Leicester",
"University of Lethbridge",
"University of Lima (Universidad de Lima)",
"University of Lincoln",
"University of Liverpool School of Law & Social Justice",
"University of Liège",
"University of Lomé",
"University of London",
"University of Lucknow",
"University of Luxembourg",
"University of Macao",
"University of Macedonia",
"University of Malaga",
"University of Malakand",
"University of Management & Technology",
"University of Manitoba",
"University of Mannheim",
"University of Melbourne",
"University of Milan",
"University of Milan Bicocca",
"University of Mines and Technology",
"University of Minho - Campus of Gualtar (Universidade do Minho - Campus de Gualtar)",
"University of Montreal",
"University of Moulay Ismail",
"University of Mumbai",
"University of Murcia",
"University of Münster",
"University of Nairobi",
"University of Namibia",
"University of Namur (Université de Namur)",
"University of Nantes",
"University of Naples \"L'Orientale\"",
"University of Naples Federico II",
"University of National and World Economy",
"University of Neuchâtel",
"University of New Brunswick",
"University of New Brunswick Saint John (UNBSJ)",
"University of New England",
"University of New York in Prague (UNYP)",
"University of Ngozi",
"University of Nigeria, Nsukka",
"University of North Carolina at Chapel Hill",
"University of Northern British Columbia (UNBC)",
"University of Nottingham",
"University of Nottingham Ningbo China",
"University of Oldenburg",
"University of Oslo",
"University of Otago",
"University of Ottawa",
"University of Oxford",
"University of Palestine",
"University of Paris",
"University of Passau",
"University of Peradeniya",
"University of Peshawar",
"University of Petroşani",
"University of Piraeus",
"University of Plymouth",
"University of Poitiers",
"University of Porto (Universidade do Porto)",
"University of Portsmouth",
"University of Potsdam",
"University of Pretoria",
"University of Prishtina \"Hasan Prishtina\"",
"University of Professional Studies, Accra (UPSA)",
"University of Puerto Rico Mayagūez",
"University of Pécs",
"University of Reading",
"University of Regensburg",
"University of Rochester",
"University of Ruhuna",
"University of Rwanda",
"University of Rwanda - College of Medicine and Health Sciences",
"University of Salamanca",
"University of Salento",
"University of Salford",
"University of Salzburg",
"University of Santiago de Compostela",
"University of Sargodha",
"University of Sassari",
"University of Science and Technology",
"University of Science, Malaysia",
"University of Seville",
"University of Sfax",
"University of Shanghai for Science and Technology",
"University of Sierra Leone",
"University of Silesia in Katowice",
"University of Sindh",
"University of South Africa",
"University of South Australia",
"University of South Bohemia České Budějovice",
"University of South Wales",
"University of Southampton",
"University of Southeastern Philippines",
"University of Southern Denmark",
"University of St Andrews",
"University of St. Cyril and Methodius in Trnava",
"University of St. Gallen",
"University of St. Thomas Aquinas",
"University of Strathclyde",
"University of Stuttgart",
"University of Sulaimani",
"University of Sussex",
"University of São Paulo",
"University of Tartu",
"University of Technology Bahrain",
"University of Technology Sydney",
"University of Technology of Compiègne",
"University of Technology, Jamaica",
"University of Tehran",
"University of Teramo",
"University of Texas–Pan American",
"University of The Bahamas",
"University of The Gambia",
"University of Thessaly",
"University of Toronto",
"University of Toronto Mississauga",
"University of Toronto Scarborough",
"University of Tourism, Technology and Business Studies (UTB)",
"University of Trento",
"University of Tsukuba",
"University of Turku",
"University of Twente / Universiteit Twente",
"University of Valencia",
"University of Valle",
"University of Valle (Universidad del Valle)",
"University of Victoria",
"University of Vienna",
"University of Vigo (Universidade de Vigo)",
"University of Virginia",
"University of Waikato",
"University of Wales",
"University of Wales Trinity Saint David",
"University of Warsaw",
"University of Warwick",
"University of Washington",
"University of West Hungary, Savaria",
"University of West London",
"University of Westminster",
"University of Winchester",
"University of Windsor",
"University of Wisconsin-Madison",
"University of Wolverhampton",
"University of World Economy and Diplomacy",
"University of Wrocław",
"University of York",
"University of Zanjan",
"University of Zaragoza",
"University of Zimbabwe",
"University of Zulia",
"University of Zululand - Richards bay campus",
"University of business sciences (Universidad De Ciencias Empresariales)",
"University of the Aegean",
"University of the Algarve",
"University of the District of Columbia",
"University of the East",
"University of the Free State",
"University of the Holy Quran and Islamic Sciences",
"University of the Panteios Library & Information Centre",
"University of the Philippines Diliman",
"University of the Philippines Los Baños",
"University of the Philippines System",
"University of the Philippines Visayas",
"University of the Visayas - Main Campus",
"University of the West Indies",
"University of the West Indies - Cave Hill Campus",
"University of the West of England - UWE Bristol",
"University of the Witwatersrand, Johannesburg",
"Ural Federal University",
"Ural Institute of Economics, Management and Law",
"Ural State Pedagogical University",
"Utkal University",
"Utrecht University",
"Uzbek State University of World Languages",
"V.N. Karazin Kharkiv National University",
"VNU University of Social Sciences and Humanities",
"Valladolid University",
"Valley View University",
"Vanadzor State University",
"Vancouver Film School",
"Vancouver Island University",
"Veer Narmad South Gujarat University",
"Victoria University of Wellington",
"Victoria University: Footscray Park Campus",
"Victory University",
"Vienna University of Economics and Business",
"Vietnam National University - Hanoi",
"Vietnam Union of Science and Technology ...",
"Visvesvaraya Technological University (VTU)",
"Vita-Salute San Raffaele University",
"Volgograd State University",
"Voronezh State University",
"WIZO Haifa Academy of Design and Education",
"WSB Universities",
"Wageningen University & Research",
"Walter Sisulu University",
"Warren National University",
"Warsaw School of Economics",
"Warsaw University of Technology",
"Waseda University",
"Washington State University",
"Wawasan Open University",
"Website Desgn and Development, Graphics Design and Video Production, and Elearninig center",
"Webster Vienna Private University",
"Wenzao Ursuline University of Languages",
"West University of Timișoara",
"Western Sydney University",
"Western University",
"Westminster International University in Tashkent",
"Weston College",
"Wharton School of the University of Pennsylvania",
"Wilfrid Laurier University",
"Wimbledon College of Arts",
"Windsor University School of Medicine (Cayon Campus)",
"Wisconsin International University College, Ghana",
"Wisdom University",
"Woodhouse Grove School",
"Worcester College",
"Wuhan University",
"XLRI - Xavier School of Management",
"Xavier Institute of Communications (XIC)",
"Xavier University - Ateneo de Cagayan",
"Xi'an Jiaotong University",
"Xi'an Jiaotong-Liverpool University",
"Xiamen University",
"Xidian University",
"Yadanabon University",
"Yalova University",
"Yanshan University",
"Yaounde University II",
"Yaroslav Mudryi National Law University",
"Yenching Academy",
"Yerevan Haybusak University Երեւանի Հայբուսակ Համալսարան",
"Yerevan State Conservatory after Komitas",
"Yerevan State University",
"Yerevan State University of Architecture and Construction",
"Yibin University",
"Yokohama National University",
"Yonsei University",
"York University",
"York University Glendon Campus",
"Yıldız Technical University",
"ZCAS University",
"Zagazig University",
"Zambia Institute of Mass Communications (ZAMCOM)",
"Zamorano Pan-American Agricultural School",
"Zamorano Pan-American Agricultural School (Universidad Zamorano)",
"Zeppelin University",
"Zhejiang Gongshang University",
"Zhejiang Normal University",
"Zhejiang University",
"Zhejiang University of Technology",
"Zhengzhou University",
"Zhongnan University of Economics and Law",
"Zimbabwe Open University",
"aarhus cathedral school",
"aberystwyth university",
"adirondack community college, suny",
"advanced school of mass communication - cameroon",
"agricultural university of georgia",
"almaty university of power engineering and telecommunications",
"aptech computer education",
"argentine university of enterprise",
"aschaffenburg university of applied sciences",
"asian academy of film and television",
"atma jaya catholic university of indonesia",
"austral university",
"autonomous university of barcelona",
"autonomous university of bucaramanga",
"autonomous university of nuevo leon",
"azuay university",
"bahcesehir university",
"baikal national university of economics and law",
"baikal state university of economics and law",
"bashkir state medical university",
"bay de noc community college",
"belgorod state university",
"bellevue community college",
"belmont abbey college",
"bergen community college",
"bethlehem college & seminary",
"bhadrak autonomous college",
"birsa institute of technology sindri",
"bosphorus university, turkey",
"bremen international graduate school of social sciences",
"brooks institute of photography",
"buffalo state college, state university of new york",
"bunker hill community college",
"butte community college",
"ca' foscari university of venice",
"cameroon college of arts, science and technology, bambili",
"catholic university of leuven",
"catholic university of puerto rico",
"catholic university of santa maria la antigua",
"catholic university of santiago de guayaquil",
"catholic university of santiago of guayaquil",
"catholic university of santo domingo",
"center for research and teaching in economics",
"central university of venezuela",
"charter oak state college",
"china institute of industial relations",
"christ college",
"christendom college",
"chung-ang university",
"chuvash state university",
"city colleges of chicago-kennedy-king college",
"city university of new york, baruch college",
"city university of new york, brooklyn college",
"city university of new york, hunter college",
"city university of new york, york college",
"clark college",
"college of african wildlife management",
"college of san mateo",
"college of william and mary",
"college of wooster",
"comenius university in bratislava",
"connecticut school of broadcasting",
"costa rica institute of technology",
"danish institute for international studies",
"danish school of journalism",
"davis and elkins college",
"eafit university",
"east ukrainian national university volodymyr dahl",
"efbritish college, cambridge",
"eotvos lorand university",
"eseade university institute",
"eserp business school",
"estonian academy of arts",
"europainstitut university of basel",
"european college of liberal arts, berlin",
"european institute of european and international superior studies",
"european university, geneva",
"everett community college",
"faculty of law of sao bernardo do campo",
"faculty of management sciences-uniport",
"fatih university",
"federal institute of education, science, and technology, rio grande do sul, osorio",
"federal polytechnic bauchi",
"federal university of amazonas",
"federal university of goiÃƒÂ¡s",
"federal university of itajuba",
"federal university of para",
"federal university of rio de janeiro",
"federal university of rio grande do norte",
"federal university of santa catarina",
"federal university of sao joao del-rei",
"federal university of technology, yola, adamawa state",
"felix houphouet boigny university",
"felix houphouet boigny university of cocody-abidjan",
"finger lakes community college",
"first moscow state medical university",
"fort lewis college",
"free university berlin",
"free university of berlin",
"free university of brussels",
"friedrich naumann foundation for freedom",
"fumec university",
"geneseo college, state university of new york",
"georg simon ohm technical university of applied sciences, nuremberg",
"georgia college and state university",
"georgian state agrarian university",
"german institute for economic research",
"german university in cairo",
"gibson dunn and crutcher, palo alto",
"goucher college",
"government ayesha degree college for women",
"graduate center, city university of new york",
"green mountain college",
"green river community college",
"hanze university of applied sciences",
"harper college",
"harvard college",
"hasanuddin university",
"hec montreal",
"hec montrÃƒÂ©al",
"hec school of management",
"helsinki university of technology",
"hertie school of governance",
"hertie school of governance berlin",
"highline community college",
"hope college",
"humanitarian institure",
"humber college",
"hunter college of city university of new york",
"immanuel kant state university of russia (kaliningrad state university)",
"indian institute of technology, indore",
"indiana institute of technology",
"indiana university-purdue university, columbus",
"indiana university-purdue university, indianapolis",
"indonesia university of education",
"institut catholic de kabgayi",
"integrated metropolitan college of campinas",
"inter american university of puerto rico",
"inter-american open university",
"interdisciplinary center herzliya",
"interdisciplinary center, hierzliya",
"international institute of information technology,",
"international university sek, ecuador",
"itawamba community college, fulton",
"iteso",
"jean moulin university lyon 3",
"jiangxi normal university",
"julius maximilian university of wurzburg",
"kabul education university",
"kamwenja teachers' training college",
"kazakh university of economics, finance and international trade",
"kazakh-american free university",
"kca university",
"keystone college",
"kishwaukee college",
"knoxville college",
"kyiv national university of trade and economics",
"lemoyne-owen college",
"leningrad polytechnic institute",
"lessius mechelen university college",
"lincoln, oxford university",
"lock haven university of pennsylvania",
"long beach city college",
"long island university",
"louisiana state government",
"lynchburg college",
"mackenzie presbyterian university",
"magenta training institute",
"mahidol university",
"major university, santiago",
"mercatus center at george mason university",
"metropolitan state university of denver",
"mexico autonomous institute of technology (itam).",
"middlesex county college",
"midwestern baptist college",
"modern university of humanities",
"monterrey institute of technology and higher education, monterrey",
"moscow automobile and road construction university",
"moscow institute of physics and technology",
"moscow state university of psychology and education",
"moscow state university of railway engineering",
"motion picture institute of michigan",
"mount holyoke college",
"nakawa vocational training institute",
"national technical university of ukraine",
"national technical university, kharkiv polytechnic institute",
"national university of colombia",
"national university of distance education",
"national university of san antonio abad in cuzco",
"national university of san luis",
"new college franklin",
"new university of lisbon",
"new university of lisbon, portugal",
"nichols college",
"north ossetian state university",
"northwestern michigan college",
"norwegian university of science and technology",
"novgorod state university",
"novosibirsk state technical university",
"nyenrode business university",
"odessa national academy of law",
"opole university of technology",
"osgoode hall law schoolq",
"osh technological university",
"ostroh academy national university",
"paris institute of political studies",
"parkland college",
"parthenope university",
"pennsylvania state university, worthington scranton",
"penza state university of architecture and construction",
"perm state university",
"peruvian university of applied sciences",
"pierce community college of la",
"plehanov russian academy of economics",
"plekhanov russian university of economics",
"polk community college",
"pontifical catholic university of campinas",
"pontifical catholic university of chile",
"pontifical catholic university of puerto rico",
"precarpathian national university",
"queensland university of technology",
"rajiv gandhi technical university",
"rangsit university international college (ric)",
"regenesys business school",
"rensselaer polytechnic institute",
"rhode island college",
"royal university of law and economics",
"russian academy of justice",
"russian presidential academy of national economy and public administration",
"saint catherine university",
"saint john's college-the moon",
"saint petersburg state polytechnic university",
"salt lake community college",
"samara state university of economics",
"sant'anna school of advanced studies",
"saratov state technical university",
"satyajit ray film and television institute",
"school for advanced studies in the social sciences",
"senghor university",
"siberian federal university",
"sichuan fine art institute",
"sodertorn university college",
"spartanburg methodist college",
"springfield college",
"srh university of applied sciences, berlin",
"st-petersburg state university of economics",
"st. john fisher college",
"state marine technical university of saint petersburg",
"state university of maringa",
"state university of new york, oswego",
"state university of new york, potsdam",
"state university of tetotvo - macedonia",
"sultan idris education university",
"sumy state a.s. makarenko pedagogical university",
"superior school of university studies and specialization saint anne of pisa",
"swedish defence university",
"swiss federal institute of technology",
"swiss federal institute of technology, zurich",
"tashkent state technical university",
"taylor university fort wayne",
"technical university munich",
"the academy of management and administration (wszia)",
"the college of william and mary",
"the college of wooster",
"the colorado college",
"the graduate center, cuny",
"the june buchanan school",
"the open university of tanzania",
"the polytechnic ibadan",
"the polytechnic, ibadan",
"the university of paris-est creteil (upec, formerly the university of paris 12)",
"trust international school",
"ukhta state technical university",
"un university for peace",
"united nations university for peace",
"united nations university-merit / maastricht university",
"universities of grenoble",
"university abou bekr belkaid of tlemcen",
"university jean moulin of lyon 3",
"university of ankara",
"university of antioquia",
"university of bangalore",
"university of belgrano",
"university of bologna",
"university of bordeaux",
"university of cagliari",
"university of california - san diego",
"university of california berkeley school of law",
"university of california san diego",
"university of chicago hospitals",
"university of colorado anschutz medical campus",
"university of colorado,anschutz",
"university of cuenca",
"university of debrecen",
"university of dokuz eylÃƒÂ¼l",
"university of duisberg-essen",
"university of duisburg essen",
"university of galatasaray (turkey)",
"university of genoa",
"university of genova",
"university of granada",
"university of grenoble, france",
"university of guanajuato",
"university of hagen, germany (fernuniversitÃƒÂ¤t in hagen)",
"university of havana",
"university of istmo",
"university of jyvaskyla",
"university of kinshasa",
"university of lagos",
"university of lagos, nigeria",
"university of leuven",
"university of lleida",
"university of lugano",
"university of macerata",
"university of maribor, slovenia",
"university of medellin",
"university of messina",
"university of miskolc",
"university of miyazaki",
"university of montpellier 1",
"university of new south wales",
"university of nice-sophia antipolis",
"university of nordland",
"university of ouagadougou",
"university of oxford, balliol college",
"university of oxford, brasenose college",
"university of oxford, magdalen college",
"university of oxford, saint anne's college",
"university of palermo",
"university of pelita harapan",
"university of quebec, chicoutimi",
"university of quebec, montreal",
"university of san martin de porres",
"university of san simon",
"university of sherbrooke",
"university of siena",
"university of stellenbosch",
"university of the americas, puebla",
"university of the andes, colombia",
"university of the city of manila",
"university of the pacific, lima",
"university of the republic",
"university of the valley of guatemala",
"university of ulster",
"university of uppsala",
"university of warwick - warwick business school",
"university of wisconsin, waukesha",
"university of witten-herdecke",
"university of wuppertal",
"university of yaounde",
"universtity of antwerp management school",
"urals state technical university",
"vasyl stefanyk precarpathian national university",
"volodymyr dahl east ukrainian national university",
"wagner college",
"waynesburg college",
"weber state university",
"wellesley college",
"wells college",
"west kazakhstan marat ospanov state medical university",
"west los angeles college",
"westminster college (bahamas)",
"westminster college (mo)",
"westminster college mo",
"westminster college, mo",
"worcester state college",
"yankton college",
"yeditepe university",
"yogyakarta state university, indonesia",
"yunnan nationalities university",
"İzmir University of Economics",
"جامعة الموصل - University of Mosul",
"جامعة اليرموك | Yarmouk University",
"‪Helwan university‬"
   ];
   
    $("[fs-field-validation-name='1.2 University name'] > input").autocomplete({
    source: availableTags,
      minLength : 3
});
  } );
