"walla walla university",
"walsh university",
"wartburg college",
"watkins institute college of art and design",
"waynesburg college",
"wells college",
"wesleyan college",
"west africa theological seminary",
"west donbass institution of economics and management",
"west kazakhstan marat ospanov state medical university",
"west los angeles college",
"western university of health sciences",
"westminster college",
"westminster college (bahamas)",
"westminster college (mo)",
"westminster college mo",
"westminster college, mo",
"westminster college, salt lake city",
"whittier college",
"willamette university graduate school of education",
"william rainey harper college",
"wintech computer college",
"xavier institute of social service",
"yaba college of technology",
"yale free press",
"yashwantrao chavan maharashtra open university",
"yelabuga state pedagogical university",
"yeshiva university",
"yildiz technical university",
"york college of pennsylvania",
"young india fellowship",
"yunnan nationalities university",
"yuriy fedkovych chernivtsi national university/department of political science and public administr",
"zagreb school of economics and management",
"zhejiang university of technology",
"Orebro University",
"İzmir University of Economics",
"Yarmouk University",
"‪Helwan university‬"
   ];
   
  $("[fs-field-validation-name='2.1.1) University name'] > input").autocomplete({
    source: availableTags,
      minLength : 3
});
});
